### ISSUE TITLE
Reflex 10.0 false positive.

### ISSUE THREAD

**Issue by train21** [MeGysssTaa/ReflexIssueTracker#1]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False Positive

**Server version:**
Spigot 1.8.8 (whatever your test server is.)

**ProtocolLib version:**
Same what ever version your test server is.

**Reflex version:**
10.0 

**ViaVersion version (if present):**
1.0.4 (Whatever your test server is)

**A video proving the bypass/false positive if reporting a bypass/false positive:**
Uploaded wrong file lmao. I will upload when I get a chance.

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
I dont know, it should be on your test server.

**Additional information (e.g. how to reproduce the issue you are experiencing):**
I was clicking at like 6-8 cps and I was moving quicking and as I was using ESP you can see I hit the entities.

**Comment by MeGysssTaa** [comment]
Which name have you got in-game? I'll search for you in logs.
Waiting for the video aswell.
