### ISSUE TITLE
A free client bypassing Reflex

### ISSUE THREAD

**Issue by SkillzGamingYT** [MeGysssTaa/ReflexIssueTracker#10]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
bypass

**Server version:**
USING REFLEX OFFICIAL TEST SERVER

**ProtocolLib version:**

**Reflex version:**

**ViaVersion version (if present):**

**A video proving the bypass/false positive if reporting a bypass/false positive:**
download jigsaw https://www.jigsawclient.ml/ with module "Aimbot" on setting "Click"

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:*

**Additional information (e.g. how to reproduce the issue you are experiencing):**
Add ClickAimbot Check.

**Comment by MeGysssTaa** [comment]
Not a bypass. Jigsaw's ClickAimbot just rotates you 1 (or less?) degree in a direction of your enemy each hit. If I wouldn't rotate myself, I would miss 90% hits.
