### ISSUE TITLE
Reflex loading issue

### ISSUE THREAD

**Issue by JavaTheChoder** [MeGysssTaa/ReflexIssueTracker#102]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Loading issue

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/k21F

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
just spams this over and over again https://hastebin.com/surenukusa.pl

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by JavaTheChoder** [comment]
Update: i just got this error https://hastebin.com/royuhavoji.md

**Comment by MeGysssTaa** [comment]
Caused on disable and can be safely ignored.
