### ISSUE TITLE
Lost connection error

### ISSUE THREAD

**Issue by kukubaczek** [MeGysssTaa/ReflexIssueTracker#103]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):** other

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/rUCC

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
After hitting a mob (Giant) server kicks player with reason: "[Proxy] Lost connection to the server" (bungee), console: 
[20:43:10] [Netty Epoll Server IO #6/ERROR]: java.lang.NullPointerException
[20:43:10] [Server thread/INFO]: test lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.handler.codec.DecoderException: Unable to decode datawatcher object

**Comment by sinnlosername** [comment]
Enable debug in bukkit.yml & server.properties and cause the error again. It should print a bigger error then. Please post this error here.

**Comment by kukubaczek** [comment]
Here is an error: https://hastebin.com/agusigapij.cs
