### ISSUE TITLE
NPC name in Tab, removable?

### ISSUE THREAD

**Issue by Timber22** [MeGysssTaa/ReflexIssueTracker#104]
## Reflex Bug Report
**Issue type:**
Is it possible to remove the NPC's name in tab, once the NPC goes invisible.
Or even not have the NPC show up in tab?

**Screenshot:**
https://gyazo.com/0e610792b0ebb241f94c59b78180aab0

**Additional information:**
Hit an entity until the NPC shows up, then open TAB. If it's not possible to remove this, that's okay. But others may have the same question.

**Comment by MeGysssTaa** [comment]
Only happens with single player online.
