### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by MEshitou** [MeGysssTaa/ReflexIssueTracker#108]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):*console error*

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:*https://p.reflex.rip/HC3Y*

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
[latest.zip](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1203287/latest.zip)

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
This error occurs when the player enters and moves

**Comment by MeGysssTaa** [comment]
Update ViaVersion.
