### ISSUE TITLE
Jigsaw ByPass AntiCheat

### ISSUE THREAD

**Issue by Alpheos** [MeGysssTaa/ReflexIssueTracker#110]
Hi, i have test the Hacked Client "Jigsaw" in the test server and the cheat "AirJump" bypass the anticheat :D

**Comment by Alpheos** [comment]
And fly, noslowdown, ect

**Comment by MeGysssTaa** [comment]
Please read the overview page.

**Comment by ipaidforgithub** [comment]
install NCP.

**Comment by Eyremba** [comment]
> And fly, noslowdown, ect

You seem to be really dumb @Alpheos. Reflex is only a COMBAT anti-cheat against PvP cheats.
