### ISSUE TITLE
Help me please :3

### ISSUE THREAD

**Issue by Alpheos** [MeGysssTaa/ReflexIssueTracker#111]
Hello,

I bought your anticheat a few hours ago but I confess that I do not find myself in the configuration and this affects much rendering because the anticheat does not kick / ban players! It only detects the cheats and send logs on the console.

Can you help me ?

thank you,
FoxDamage

(I'am French sorry for bad language)

**Comment by MeGysssTaa** [comment]
I don't understand what problems are you experiencing.

**Comment by Alpheos** [comment]
If you want i can pay you 2€ for config my reflex plugins x)

And for report no detected cheat where i make that ? :)

Thanx for reply :D

**Comment by MeGysssTaa** [comment]
I still don't understand anything of what are you trying to say.

**Comment by Alpheos** [comment]
:(

**Comment by Alpheos** [comment]
Ok, i have tested Reflex on 1.7.10 server with a good version of ProtocolLibs and he don't work :/
