### ISSUE TITLE
Ban/kick aren't working

### ISSUE THREAD

**Issue by ipaidforgithub** [MeGysssTaa/ReflexIssueTracker#113]
**other**

**/reflex debug: https://p.reflex.rip/S8vt**

**Log: https://pastebin.com/qS1KLWPX | Video: https://youtu.be/4c6QPHmWq7A**

**When I tested anticheat on my server it didn't kicк me.**
**When I tested it on my pc it was spamming Reflex » Invalid player.**

**Comment by MeGysssTaa** [comment]
Please record the video again, with /reflex verbose enabled. Also enable general.async_exception_logging and check console for errors again. Also make sure to test this in combat/pve, because invisible NPCs exist to harden the AntiBot filter, hitting them give you no any flags.

**Comment by ipaidforgithub** [comment]
New video with heuretics only: https://youtu.be/KelE2RLO0co
Log with spammed invalid player: https://pastebin.com/uAXNvcWp

**Comment by MeGysssTaa** [comment]
Try using another kick command then. And did you enable general.async_exception_logging?

**Comment by ipaidforgithub** [comment]
config
https://pastebin.com/ffz3rzt2

**Comment by ipaidforgithub** [comment]
Fixed. I'm just need to add space after %player% in default kick messages. (Beacuse of color codes placeholder will be %player%&fStop hacking!)
