### ISSUE TITLE
reflex feature "cancel_vl" (config)

### ISSUE THREAD

**Issue by hamaplay** [MeGysssTaa/ReflexIssueTracker#115]
**Issue type (console error/false positive/bypass/other):**
other (Feature)

The "cancel_vl" config-option should allow cancelling illegal actions after a specific violation-level.
So for example:
if the "cancel_vl" is set to 6 in the BuildActions Check, nothing will be cancelled unless the violation Level (in this case, 6) is reached. Every violation after this will be cancelled.

**Comment by Vktre** [comment]
Skid
