### ISSUE TITLE
OutOfMemoryError still appears using 10.1-2U

### ISSUE THREAD

**Issue by BeProudMC** [MeGysssTaa/ReflexIssueTracker#118]
Issue type: Console error

PaperSpigot version: http://prntscr.com/gdbq9m (Latest 1.7.10 PaperSpigot)
Reflex version: v10.1-2U

Do /reflex debug, and paste here the link you've got. Keep empty if on test server:
Commands are not working at the moment for me, looks like the plugin can't register their listener.
However, here is a screenshot of the error, that appeared in the console after starting the server:
http://prntscr.com/gdbsw0

Details: I have a stable internet connection and allocated my server 4gb (should be enough) ram.

**Comment by Vktre** [comment]
What protocolib version?

**Comment by MeGysssTaa** [comment]
Please post the error itself.

**Comment by BeProudMC** [comment]
I'm using ProtocolLib 3.7.0, and I forgot to mention that I'm using the Google Lib plugin as well.
Here's the full console log: https://pastebin.com/q1PGVRBq (Error does not belong to my custom plugins)
