### ISSUE TITLE
False Pos

### ISSUE THREAD

**Issue by Spoooooooky** [MeGysssTaa/ReflexIssueTracker#12]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):** False Positive

**Server version:** 1.8.9

**ProtocolLib version:** Whichever the server uses

**Reflex version:** Whichever the server uses

**ViaVersion version (if present):** Not sure what this is 

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=LtD7d2981wo&feature=youtu.be

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=LtD7d2981wo&feature=youtu.be

**Additional information (e.g. how to reproduce the issue you are experiencing):**
No idea I just jitter clicked

**Comment by MeGysssTaa** [comment]
Don't use double-clicks or whatever enchancing click speed.

**Comment by Spoooooooky** [comment]
I was not using double clicks - I was clicking fast like I usually do

**Comment by Spoooooooky** [comment]
I was clicking at my legit normal speed and it kicked me

**Comment by MeGysssTaa** [comment]
It's impossible for human to constantly click with a delay of 0 milliseconds for over a minute.

**Comment by Spoooooooky** [comment]
Do you have any way for me to contact you? I will go on a screenshare while
testing it.

**Comment by Spoooooooky** [comment]
Nevermind - your AC is right - I believe my mouse does double click.

**Comment by Spoooooooky** [comment]
Nevermind I don't think it does

**Comment by MeGysssTaa** [comment]
I have logs for you, and clicking without any delay for a long time is actually what you are kicked for.

**Comment by Spoooooooky** [comment]
I definitely had a delay because I have tested the events of my mouse and it's 30-50ms between events at the speed at which i click. This is around 12-16cps.
