### ISSUE TITLE
bannedPlayers.json does not save on server stop

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#121]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error / other

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:** 
Console error: https://p.reflex.rip/EUKi.vbs

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
When stopping the server, the bannedPlayers.json file fails to save.

Java: 1.8.0_131
Server: Paper/git-Paper-1190 (MC: 1.12.1)
Reflex: 10.1-2U
Protocollib: 4.4.0-SNAPSHOT-b385

**Comment by Vktre** [comment]
It says that the bannedplayer.json is already uaed by a another process.

**Comment by MatrixTunnel** [comment]
Yep! My guess is that Reflex opens it more then once or does something weird when it's trying to save it
