### ISSUE TITLE
Bungeecord kick

### ISSUE THREAD

**Issue by mariolars** [MeGysssTaa/ReflexIssueTracker#122]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

https://pastebin.com/VJwMKG8c

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

No idea what is happening. Some players get random kicks with error that i gave above.

**Comment by MatrixTunnel** [comment]
Can you provide more information please (i.e. A link to a `/reflex debug` paste and your Bungee/Waterfall version)

**Comment by MeGysssTaa** [comment]
Not related to Reflex, or not all the stacktraces have been providen.

**Comment by mariolars** [comment]
Travertine version git:Travertine-Bootstrap:1.12-SNAPSHOT:87afa32
Paper version git-Paper-1178
ProtocolLib v4.4.0-SNAPSHOT-b385
Well i disabled reflex and players dont receive kicks anynmore. I don't want to restart server again for now because i dont want to interrupt my players I will install it again tomorrow morning and will provide any output from debug command.
UTC+02:00

**Comment by MatrixTunnel** [comment]
After looking into Travertine, I'm pretty sure that is the cause of the issue since it hasn't been updated for a while now. 

My recommendation is to use the latest Waterfall and try using ProtocolSupport for 1.7 clients (if that's what you're wanting to use it for). I also recommend updating Paper but I don't really know how your network is setup so it's up to you.

**Comment by mariolars** [comment]
https://p.reflex.rip/orKP
https://zapodaj.net/ac09f0cd60adf.png.html
https://hastebin.com/uxogovicuj.md

**Comment by mariolars** [comment]
Switching to hexacord fixed issue.
