### ISSUE TITLE
InvActions spam

### ISSUE THREAD

**Issue by kukubaczek** [MeGysssTaa/ReflexIssueTracker#124]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):** other

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):** When player is using InvActions plugin don't recognizes enabled bypass by command (it spam kick command)

**Comment by MeGysssTaa** [comment]
Don't erase issue template. Fill it fully. You should provide proofs and /reflex debug.
