### ISSUE TITLE
[Not fixed in latest version of reflex]  Kicking Problem

### ISSUE THREAD

**Issue by lolo773** [MeGysssTaa/ReflexIssueTracker#125]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
other

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/asER

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
![default](https://user-images.githubusercontent.com/22345894/29855951-3b7f4d86-8d82-11e7-9201-cd3d302cd992.png)

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
When i'm testing with my alt. Reflex seems kicked with this reason...

**Comment by MeGysssTaa** [comment]
This is most likely caused by using 53489852110065 anticheats at the same time...

**Comment by lolo773** [comment]
What's that mean =0
I am using 
AAC NCP and Spartan
Together with reflex :[

How to fix it?

**Comment by lolo773** [comment]
Also aac addition pro too :P

**Comment by MeGysssTaa** [comment]
You shouldn't use that many anticheats.
