### ISSUE TITLE
KillAura Bots prevent to build

### ISSUE THREAD

**Issue by H1rntot** [MeGysssTaa/ReflexIssueTracker#126]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
other

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/kL8W

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://youtu.be/8-hFrxV4X5c

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
When i hit a Player, the killaura bots are prevent to build. The Client is only use to see the bots.

**Comment by lolo773** [comment]
Seems bad yo players
