### ISSUE TITLE
Add vanilla/squidhq to paranoid mode of clientcontrol

### ISSUE THREAD

**Issue by Janmm14** [MeGysssTaa/ReflexIssueTracker#128]
Add vanilla/squidhq to paranoid mode of clientcontrol.

https://squidhq.com/

**Comment by Eyremba** [comment]
I don't think that SquidHQ launcher will stay available for a long time - I already talked with Mojang about DMCA requests against SquidHQ.

**Comment by Janmm14** [comment]
Atm it is just as legit as "vanilla" is claiming, so why not enable it?

I don't think mijang will dmca that, else they would've dmca'd wurst's download repositories already.

**Comment by Eyremba** [comment]
> I don't think mijang will dmca that, else they would've dmca'd wurst's download repositories already.

*Funny smile*

--> https://github.com/Wurst-Imperium/Wurst-MC-1.8

"Repository unavailable due to DMCA takedown.

This repository is currently disabled due to a DMCA takedown notice. We have disabled public access to the repository. The notice has been publicly posted. "

So as you can see, they are taking it all down.

> Atm it is just as legit as "vanilla" is claiming
...but it bypasses the Mojang blacklist, and Mojang is annoyed because of this.

**Comment by Janmm14** [comment]
@Eyremba I don't think mojang takes things seriously they would've dmca'd their new repository https://github.com/Wurst-Imperium/Wurst-MCX2/releases

**Comment by Eyremba** [comment]
@Janmm14 maybe they did that too but it takes time for Github to handle the DMCA requests? (They get a lot of them). Also, it will get his account banned when he reuploads the stuff to other repositories.

**Comment by FinalPacket** [comment]
@Eyremba don't worry about @Janmm14 he doesn't understand very much, neither in spigot threads.
A DMCA has to go through the courts and it also has to go through a legal process, so it would take time.

**Comment by sinnlosername** [comment]
@FinalPacket Nope. If a provider receive a dmca, he has to take the resource own, asap. Also, don't be rude.

**Comment by FinalPacket** [comment]
To issue a DMCA complaint, it needs to go through a court. That's what I meant, yes they have to take it down but please read.
