### ISSUE TITLE
NPC dies? And false kicked!

### ISSUE THREAD

**Issue by ItsMennyo** [MeGysssTaa/ReflexIssueTracker#13]
This was your test server so that information other than what should.

1. If you made a villager died kind of NPC behind you suddenly gone. Only when you join again until he came back

2. If you have two villagers in a corner and then two beats (very fast in turns) then you get kicked for "Non-vanilla combat patterns" And kick ID is "*h\J7@Hn0@et"

And I had no hacks to (1.11.2 Optifine)

Sorry for my bad English!

**Comment by MeGysssTaa** [comment]
Video proofs? If no any, the issue will be closed.

**Comment by ItsMennyo** [comment]
Okay it was all a very long time before the villager died so I'll see if I manage again but I must go to school so maybe video comes at the end of the day (If the NPC is dead again).

**Comment by ItsMennyo** [comment]
The video is now rendering because I was 20 minutes trying to get that dead villager but when a player got there and it worked on so I have proof, I think he is ready within 5/10 min online

**Comment by ItsMennyo** [comment]
The video I also added some more stuff shows: https://www.youtube.com/watch?v=yQQoE3wycdM

What strikes me after the rendering was that at 1:18 also sees the side players (of the Forcefield check) go also die.

**Comment by MeGysssTaa** [comment]
Yes, definitely looks like a false positive..
`[12:16:30] Reflex 10.0: ItsMennyo KillAura 23 (+23) | cps: 14 | ping: 25 | tps: 20,0
[12:16:54] Reflex 10.0: ItsMennyo KillAura 27 (+27) | cps: 22 | ping: 25 | tps: 19,53
[12:17:59] Reflex 10.0: ItsMennyo KillAura 94 (+94) | cps: 57 | ping: 26 | tps: 20,0`

**Comment by ItsMennyo** [comment]
Yep, so you already know something of a solution?

**Comment by MeGysssTaa** [comment]
You don't understand? Are you really trying to make me believe you are doing 20+ cps without an autoclicker?

**Comment by ItsMennyo** [comment]
I do not use autoclicker or something else. But the CPS increases achieved mine was about 18...

**Comment by ItsMennyo** [comment]
I just want make Reflex better so I see myself as a kind of tester and therefore I do not use autoclicker. But I do not understand that the plugin say I have a CPS of 57? I think there is something to the server/plugin itself light. Perhaps it was because of that NPC and Forefield checks were broken?
