### ISSUE TITLE
Lag at the start of the fight

### ISSUE THREAD

**Issue by BumCykMyk** [MeGysssTaa/ReflexIssueTracker#133]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Lag at the start of the fight

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/0goH

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://youtu.be/Hn-G4w-AI-I
https://youtu.be/qcmxz0CWkE8

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
As a player starts the fight, he can not hit the player for about 10 seconds
When the killaura is on the true

**Comment by MeGysssTaa** [comment]
You shouldn't skip issue template fields...
You should also provide reflex debug, reflex timings and reflex dump.
