### ISSUE TITLE
Killaura False Positive

### ISSUE THREAD

**Issue by ItzSomebody** [MeGysssTaa/ReflexIssueTracker#139]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):** False Positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:** This was on the test server

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:** https://youtu.be/nJXa5KqP4Oo

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
1. Go to the area where all the villagers are.
2. Start hitting them so that they are knocked back in a straight line
3. Keep doing it for awhile

**Comment by MeGysssTaa** [comment]
"False positive" means you have been **kicked** falsely. It's supposed that you get some flags sometimes.
