### ISSUE TITLE
Reflex 10.0 Testserver False Positive

### ISSUE THREAD

**Issue by CriZZiDevelopment** [MeGysssTaa/ReflexIssueTracker#14]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
false positive

**Server version:**
1.8 - 1.11 (ViaVersion) server

**ProtocolLib version:**
I don't know which version your server uses.

**Reflex version:**
10.0

**ViaVersion version (if present):**
I don't know which version your server uses.

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://youtu.be/VLjBb-KMEUs
In this Video i am using minecraft 1.8.9 optifine with betterfps!

**Comment by jiangdashao** [comment]
xD  
where is the author?(•́ω•̀ ٥)

**Comment by MeGysssTaa** [comment]
Try to reproduce this again. Many fixes were done yesterday.

**Comment by CriZZiDevelopment** [comment]
I can reproduce it.

**Comment by CriZZiDevelopment** [comment]
Mhh. I have done it again one or two times but then I didn't get kicked. I think its almost fixed. But not completely.

**Comment by CriZZiDevelopment** [comment]
I think its fixed now!
