### ISSUE TITLE
Player freezing when fighting

### ISSUE THREAD

**Issue by geroalex** [MeGysssTaa/ReflexIssueTracker#141]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**

Other and console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

https://p.reflex.rip/KA9l

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

https://youtu.be/Pr5pXV9zloM

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Before it freezes the player it gives this error:

https://p.reflex.rip/2lag.vbs

**Comment by Eyremba** [comment]
Please post stacktraces only via https://p.reflex.rip/

**Comment by geroalex** [comment]
Eyremba I have updated the issue.

**Comment by geroalex** [comment]
Please someone can respond?
