### ISSUE TITLE
Reflex onPacketReceiving Console Error

### ISSUE THREAD

**Issue by CorruptedCodes** [MeGysssTaa/ReflexIssueTracker#143]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console Error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/dMX0

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://pastebin.com/rMH34nb1

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by sinnlosername** [comment]
Could you try to reinstall reflex & protocollib?

**Comment by CorruptedCodes** [comment]
Sorry I didn't look through the error properly. Should've known it was a ProtocolLib error. Thanks :)
