### ISSUE TITLE
Reflex BYPASS

### ISSUE THREAD

**Issue by lolo773** [MeGysssTaa/ReflexIssueTracker#146]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Bypass

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/wMMv

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=qZ5IKXvTdEE&feature=youtu.be

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Please fix that Flux can bypass the ghost setting of flux :]

**Comment by MeGysssTaa** [comment]
The only thing you do in the video is just hitting a player 2 blocks away. Nothing legit player's can't do.
