### ISSUE TITLE
Killaura NPC Problem

### ISSUE THREAD

**Issue by YONONH** [MeGysssTaa/ReflexIssueTracker#151]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
-

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
-

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
console error
`DataMan inconsistencies: missing online players (1) | wrong number of online players (8 instead of 9)`
when people's hit players or zombies it's have NPC behind him and have this message.

**Comment by MeGysssTaa** [comment]
It's not Reflex error.
