### ISSUE TITLE
False detects

### ISSUE THREAD

**Issue by Sklave21** [MeGysssTaa/ReflexIssueTracker#156]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
false positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
The users on our server which have many cps with jitter-clicking get a very high killaura lvl although they often do not use hacks

**Comment by MeGysssTaa** [comment]
Missing debug, missing proofs.
