### ISSUE TITLE
Could not load 'plugins/Reflex-10.2-1U.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by ArtNRG** [MeGysssTaa/ReflexIssueTracker#157]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
Плагин вообще не загрузился

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
git-Paper-1239 (MC: 1.12.2)
Reflex-10.2-1U
Libs4Paper v1.0
ProtocolLib v4.4.0-SNAPSHOT-b389

**Comment by Janmm14** [comment]
error is known, use old version until fix is published
