### ISSUE TITLE
Reflex false positive (on officiel test server) 

### ISSUE THREAD

**Issue by hugo4715** [MeGysssTaa/ReflexIssueTracker#16]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False positive

**Server version:**
test.reflex.rip

**ProtocolLib version:**
test.reflex.rip

**Reflex version:**
test.reflex.rip

**ViaVersion version (if present):**
test.reflex.rip

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://youtu.be/Ejq4N8HAdgw

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
ban id https://youtu.be/Ejq4N8HAdgw

**Additional information (e.g. how to reproduce the issue you are experiencing):**
I just clicked at my maximum (around 8-10 max)

**Comment by MeGysssTaa** [comment]
Made those checks less strict, should be solved.

**Comment by hugo4715** [comment]
is the server up to date?

**Comment by MeGysssTaa** [comment]
Yes, it is. Found any more? (If so, record a new video please.)
