### ISSUE TITLE
Error Reflex AutoBan

### ISSUE THREAD

**Issue by VinnyPLV** [MeGysssTaa/ReflexIssueTracker#160]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console Error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
Paste: https://p.reflex.rip/J4ld

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
Screen about the error: https://i.gyazo.com/98e9ba871fc2b89b2eda14c974eba37a.png

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
I just put the addons on the plugins directory, after I started the server and the error shows up. The addons doesn't edit anything of the reflex's config. I also tried to edit the config by putting the modifications that are in the addons page, but they seems pretty old infact the plugin doesn't work.

**Comment by MeGysssTaa** [comment]
1. It's **Reflex** repository, **not** ReflexAutoban repository...
2. ReflexAutoban is outdated.
