### ISSUE TITLE
Bypassing

### ISSUE THREAD

**Issue by LoYungSum** [MeGysssTaa/ReflexIssueTracker#161]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
bypass.

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
I can't, I am in the official test server.

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
sry, my computer cannot handle the recording programme.

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
I just get into a hacked client and speed, Blink, ScaffoldWalk, Tower works

**Comment by Janmm14** [comment]
Speed and Blink are not checked by Reflex.

Without providing a video or at least the client's name and a download link there is nearly nothing the developers can do, so it might be a good idea to provide such logs.
