### ISSUE TITLE
Could not load 'plugins/Reflex-10.2-1U.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by JavituRec** [MeGysssTaa/ReflexIssueTracker#162]
**Issue type (console error/false positive/bypass/other):**
https://hastebin.com/ojizewaqin.sql

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Server version 1.8.8 paperspigot
ViaVersion: No
Nocheatplus: Yes
Protocollib: Last update

**Comment by Janmm14** [comment]
Duplicate.
