### ISSUE TITLE
Bug and false positives Badpackets

### ISSUE THREAD

**Issue by JavituRec** [MeGysssTaa/ReflexIssueTracker#164]
**Issue type (console error/false positive/bypass/other):**

Other: https://hastebin.com/areyopasem.pl

And I received many false positive of badpackets: https://hastebin.com/eyofazakut.pl

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

https://p.reflex.rip/f18W

**Comment by Janmm14** [comment]
Your log contains badpacket violations of multiple people. which ones are false positives or are all those false positives?

**Comment by MeGysssTaa** [comment]
Outdated version.
