### ISSUE TITLE
Kicking players in / after fight 

### ISSUE THREAD

**Issue by Hyronymos** [MeGysssTaa/ReflexIssueTracker#165]
Debug: https://p.reflex.rip/oe1c
Log: https://hastebin.com/osowetaved.vbs
Video: https://www.youtube.com/watch?v=WDwBa8Patag&feature=youtu.be

Bug only happens, if Reflex is installed!

**Comment by Janmm14** [comment]
Lemme guess: bungee log shows #154

**Comment by Hyronymos** [comment]
https://hastebin.com/ofakegejox.sql (player: jolliclp)

**Comment by Hyronymos** [comment]
https://pastebin.com/V0Kuwws6
