### ISSUE TITLE
InvActions FP

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#173]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
false positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://streamable.com/2rmdc

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
1.12 only (might be 1.9-1.11 but I haven't tested)

**Comment by MeGysssTaa** [comment]
Does this still happen with the latest version?

**Comment by MatrixTunnel** [comment]
Still happens on latest Reflex https://streamable.com/t9bwj

**Comment by MatrixTunnel** [comment]
Happens on the test server too https://streamable.com/mjzlm
Make sure you're using 1.12.x and shift clicking the item as soon as you open your inventory

**Comment by elstur** [comment]
Don't know if I should make a new bug report for it or not, but, I found that shift+clicking to get all of the same block out of your inventory in 1.12 doesn't work and if you try it repeatedly it also creates a false positive.

Sounds like the same bug, but you don't need to be moving to make it happen.

**Comment by MeGysssTaa** [comment]
@elstur please open a separate issue.

**Comment by johand199** [comment]
seems to be when you time it perfect with fall, like tested here with jump boost 
https://youtu.be/hRUO8Di4JnA

**Comment by MatrixTunnel** [comment]
Are you still having problems reproducing this issue? I’ll test it again later today but I’m pretty sure it still happens. I thought it might be my high ping to the test server but it happens locally
