### ISSUE TITLE
Reflex Running in Offline Mode

### ISSUE THREAD

**Issue by Elytrarennen** [MeGysssTaa/ReflexIssueTracker#176]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Reflex Running in Offline Mode without touching anything.

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/yoUv

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://hastebin.com/bewewenicu.md

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by Janmm14** [comment]
Apparantly an issue in relation to the encapsulation shit in iava 9.
