### ISSUE TITLE
Disable parts of ScaffoldWalk Check (like killaura)

### ISSUE THREAD

**Issue by hamaplay** [MeGysssTaa/ReflexIssueTracker#178]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**

feature request

Create a „disabled-checks“ list like in the killaura configuration for scaffoldwalk in order to disable several types of the scaffoldwalk checks (like type G etc.)

**Comment by MeGysssTaa** [comment]
Added this to all checks.
