### ISSUE TITLE
Integer Overflow

### ISSUE THREAD

**Issue by riyrus** [MeGysssTaa/ReflexIssueTracker#182]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console Error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/4YEb

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
Every time someone is hacking I get this error.
https://hastebin.com/ihalemovuz.bash
I am testing on my test server. Reflex began working for a while until I just edited the prefix on my config and it no longer works. I even reset the config

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
I have two accounts on. One is the staff, and the other is the hacker. I download Reflex from the spigot page and imported it into my server plugins folder. Then I took both accounts and joined the same server. Reflex began working when I installed it, but then after editing the config and only changing the prefix. It does not work and keeps giving me the same error. I even reset the config and It does the same thing and does not kick the person that is hacking.

**Comment by MeGysssTaa** [comment]
Try removing any files related to Reflex and fully redownloading and reinstalling it.

**Comment by riyrus** [comment]
It keeps giving me the same error, and does not kick the hacker

**Comment by MeGysssTaa** [comment]
Wait for an update and then try again with the new version, please.
