### ISSUE TITLE
Reflex False Killaura Flags

### ISSUE THREAD

**Issue by AivaruxxLTU** [MeGysssTaa/ReflexIssueTracker#183]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=0Yu8iXiSvlA&feature=youtu.be

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Just spam click the enemy at 1 place and dont move mouse pretty much

**Comment by MeGysssTaa** [comment]
There're some problems with our test server at the moment. Not Reflex's issue.
