### ISSUE TITLE
Still bugs/ false flags with one place hittin

### ISSUE THREAD

**Issue by AivaruxxLTU** [MeGysssTaa/ReflexIssueTracker#184]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/7hhQ

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=C6rcRAiNx6g&feature=youtu.be

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Just spam click at 1 spot and somehow you get "flagged"

**Comment by MatrixTunnel** [comment]
I'm pretty sure this was fixed with #166 but the plugin hasn't updated yet. If you could make another video doing the same thing with the verbose toggles on, it would help speed up the fixing process

**Comment by MeGysssTaa** [comment]
（１）Missing Reflex logs / verbose. You should include Reflex logs/verbose (flags) relevant to this player.
（２）Video must be first-view (**you** should be the one who records the video).
（３）Video must contain proofs that you are completely legit.
