### ISSUE TITLE
Task #1092 for Reflex v10.2-3U generated an exception

### ISSUE THREAD

**Issue by Astoric** [MeGysssTaa/ReflexIssueTracker#197]
## EDIT: Updating to 1.8.8 resolves the issue

By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/wUwZVk). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/wUwZVk) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ Console Error

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/2CIw

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/t9W0.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ 

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/5fc6.md

**Comment by MatrixTunnel** [comment]
After testing and talking through the error on Discord with the issue creator, this appears to be an issue with 1.8 Paper. Updating to 1.8.8 Paper fixes the issue and also fixes security issues with earlier versions of Minecraft itself
