### ISSUE TITLE
Entity bugs

### ISSUE THREAD

**Issue by Mxra** [MeGysssTaa/ReflexIssueTracker#198]
Bypass／false positive／bug／console error／feature request／question
＞ Bug

**1)** Looking directly down on TacoSpigot 1.8.8-b28 will cause an entity to be directly under you, preventing the ability to break the block directly under you. (Appears to only happen after you get combat tagged. Might be the same with the one below)

**2)** The entities will randomly hang around. Just standing there doing nothing (not even moving) in random places.

**Comment by MeGysssTaa** [comment]
Missing debug, dump and evidence.

**Comment by Mxra** [comment]
I told you how to recreate it. Don't be THAT lazy lmao

**Comment by MatrixTunnel** [comment]
He isn’t being lazy. He asked for those things so he can properly evaluate the problem and recreate the issue so it can be properly fixed. Not providing details is just as bad as saying the plugin doesn’t work without giving the reason/explanation.

**Comment by Mxra** [comment]
@MeGysssTaa 
Here's a reflex debug: https://p.reflex.rip/z3nZ
Here's a reflex dump: https://p.reflex.rip/WvCs.md
Video is uploading now.

**Comment by MatrixTunnel** [comment]
You're missing the Libs4Paper plugin which is required to run Reflex on a Paper/Taco server. You can find the plugin here: https://go.reflex.rip/libs

**Comment by johand199** [comment]
https://youtu.be/EKVq8Pql2Tc
^ can confirm on official test server

**Comment by Mxra** [comment]
@MatrixTunnel Your responses to this topic are about as useful as a doormat.
