### ISSUE TITLE
Reflex KillAura fp (entity raytrace)

### ISSUE THREAD

**Issue by wiepie** [MeGysssTaa/ReflexIssueTracker#199]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/wUwZVk). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/wUwZVk) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ false positive

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/THjU

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/RqU5.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ no errors

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/emqp.pl

### Erase everything written below if this is not a bypass or a false positive report
**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ you need to hit the person a lot of times with a steady mouse click, i always did it without a weapon so just hitting with the hand

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞ 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://www.youtube.com/watch?v=9xovxJud4y8

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞

**Comment by pEwViktor** [comment]
It looks like they have modified combat/knockback?

**Comment by wiepie** [comment]
I don't got any plugin i know that modifies knockback neither combat. Maybe a plugin secretly is doing it but that would be weird

**Comment by pEwViktor** [comment]
It has to be he is moving really wierd.

**Comment by pEwViktor** [comment]
Is it just me that think he is moving wierd @everyone

**Comment by wiepie** [comment]
I don't know, I only got spartan that might modify movement

**Comment by pEwViktor** [comment]
Try removing spartan or any plugin you think might modify knockback then try to reproduce.

**Comment by wiepie** [comment]
yeah, the npcs are not moving at all so it is probably caused by a incompatible plugin. will remove them one by one to see which plugin it is

**Comment by pEwViktor** [comment]
Good

**Comment by wiepie** [comment]
anybody maybe knows which plugin is most likely to block NPCs from moving/spawning and causing weird movement stuff? https://gyazo.com/c497b3ddb0417935dff0c54e1df6e68a

**Comment by pEwViktor** [comment]
What is anticheat inform?

**Comment by wiepie** [comment]
fixed
It was casued by hydra's tablist feature
