### ISSUE TITLE
Dragon 1.11.2 Bug

### ISSUE THREAD

**Issue by eliasjtg** [MeGysssTaa/ReflexIssueTracker#2]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False positive

**Server version:**
1.11.2

**ProtocolLib version:**
4.2.0-SNAPSHOT-b335

**Reflex version:**
9.9

**ViaVersion version (if present):**
1.0.4

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://youtu.be/nWChPAYpf6Y

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
------------------------------------------------------------------------------
 * ReflexAutoban has been enabled.

sasuke13579      |       COMBAT_REACH         (10)
sasuke13579      |       COMBAT_REACH         (10)
sasuke13579      |       COMBAT_REACH         (10)
sasuke13579      |       COMBAT_REACH         (10)

**Additional information (e.g. how to reproduce the issue you are experiencing):**
It is a false positive with the check reach, when hitting the dragon by the head, raise a little to the player and it detects it like hack.

**Comment by MeGysssTaa** [comment]
Please report only 10.0+ bugs here.
