### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by OWERLORD01** [MeGysssTaa/ReflexIssueTracker#20]
## Question
As i'm not able to spawn a dragon on offical test server, I want to ask you something:
Is the enderdragon/ghost bug fixed? On Reflex 9.9 when a player is hitting ender dragon/ghost he got kicked (probably because of frontentity, i'm not use). I think that happen when hitting wither, but i'm not sure. So.. is this problem fixed in b10?

### Thanks

**Comment by MeGysssTaa** [comment]
Yes, this doesn't happen in 10.0.
