### ISSUE TITLE
BlockActions FP

### ISSUE THREAD

**Issue by Hyronymos** [MeGysssTaa/ReflexIssueTracker#200]
Reflex Log: https://hastebin.com/upafukabew.rb
Player Debug: https://p.reflex.rip/uAy6

Video: https://youtu.be/Krep5fWn-XQ

**Comment by Hyronymos** [comment]
why won't fix? huh?

**Comment by MeGysssTaa** [comment]
Can be fixed via configuration setting: **blockactions.min_bridge_delay** (should be something a bit less than "bs: N" value you get in verbose. Try setting it to **200**.
