### ISSUE TITLE
Add a option to disable npcs/new kick system

### ISSUE THREAD

**Issue by jiangdashao** [MeGysssTaa/ReflexIssueTracker#206]
* Add a option to enable/disable FrontEntity check and NPC check, because FrontEntity check is unfriendly in pro pvp servers

* Add a Max Ping option to lag players to disable their FE detection and NPC detection 

* Make kick command in language option:
such as:

 kickformat:

– "< Reflex >"

– "You were kicked because of hacking:"

– "Reason/Hack: %reason%"

– "kickID: %kickid%"

And we just input /reflex kick reason,such as /reflex kick KillAura/Aimbot

😁

**Comment by johand199** [comment]
"Add a Max Ping option to lag players to disable their FE detection and NPC detection"

  # Should Reflex be more lenient, or even disable some
  # of the checks, for players who are lagging?
  lag_leniency: true

  # If a player is lagging for the amount of ticks provided below,
  # he will no longer be analysed by some of the checks.
  # Only effective if "lag_leniency" is set to true
  lag_threshold: 4

  # A player is no longer checked by most of the checks
  # if he is having ping greater than this (milliseconds)
  # Only effective if "lag_leniency" is set to true
  max_ping: 300

  # If server TPS drops down this value, most of the
  # checks will disable until TPS will normalize.
  # Only effective if "lag_leniency" is set to true
min_tps: 18.5

**Comment by jiangdashao** [comment]
@johand199 
nope
i know reflex already has max ping
but
it will be better that add a special max ping option for Front Entity check and NPC check

**Comment by MeGysssTaa** [comment]
・FrontEntity is one of the most effective checks and it has completely no any impact on legitimate players. 
・"MaxPing" already exists generally and it is unnecessary to add separate options for different components.
・Just use commands ._. It's not hard to copy-paste one command to several checks. Moreover, command system which we currently have allows much more customization per check than the language system you suggest.
