### ISSUE TITLE
Console Error - EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by dobrac** [MeGysssTaa/ReflexIssueTracker#21]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console error:

**Server version:**
1.8.8

**ProtocolLib version:**
3.7-SNAPSHOT-b232

**Reflex version:**
10.0-1U

**ViaVersion version (if present):**
1.0.3

**A video proving the bypass/false positive if reporting a bypass/false positive:**
///

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
https://hastebin.com/ecowucukah.bash

**Additional information (e.g. how to reproduce the issue you are experiencing):**
I think, that it prevents commands executing

**Comment by MeGysssTaa** [comment]
Outdated ProtocolLib. Use 4.2.
