### ISSUE TITLE
KillAura Coincidence False Positive

### ISSUE THREAD

**Issue by UnioDex** [MeGysssTaa/ReflexIssueTracker#219]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ False Positive

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/Gsz3

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/sUYJ.rb

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/nZlq.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/mLRY.rb

### Erase everything written below if this is not a bypass or a false positive report
**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ Player kicked with that ID: #AGVU7RQM while PvP'ing normally. In logs it says coincidence i dont understand what is it. Can you explain it please?

**Comment by MeGysssTaa** [comment]
Missing video-evidence

**Comment by UnioDex** [comment]
It is a player report and i just want to know what is that ID says.

**Comment by MeGysssTaa** [comment]
IDs say nothing. It's just the command execution number which's only use is to simplify searching certain violations in logs.
