### ISSUE TITLE
Console error - mysql connection

### ISSUE THREAD

**Issue by dobrac** [MeGysssTaa/ReflexIssueTracker#22]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Server version:**
1.8.8

**ProtocolLib version:**
3.7-SNAPSHOT-b232

**Reflex version:**
10.0-1U

**ViaVersion version (if present):**
1.0.3

**A video proving the bypass/false positive if reporting a bypass/false positive:**
///

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
https://hastebin.com/hijeyovune.sql

**Additional information (e.g. how to reproduce the issue you are experiencing):**

**Comment by jiangdashao** [comment]
Why you use ProtocolLib3.7? It is old version

**Comment by dobrac** [comment]
Does it matter in this case?

**Comment by ItsMennyo** [comment]
Sometimes @dobrac 😋
