### ISSUE TITLE
console error / reflex not working

### ISSUE THREAD

**Issue by northrix** [MeGysssTaa/ReflexIssueTracker#223]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

console error

＞ 

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/yxE8

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ server didn't crash

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞  https://p.reflex.rip/AcbV.vbs

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/CAp1.vbs

**OTHER**

reflex latest version
spigot 1.8
protocolib latest version
just logged in and hitted a villager legit and then with killaura
(console error in both stages)

＞

**Comment by MeGysssTaa** [comment]
Update to Spigot 1.8.8 and try again.

**Comment by northrix** [comment]
now its not trowing errors and it spawns the invisible npcs that chek for killaura
but it doesn't kick when i use killaura (and no im not op on the server)
and other cheats like auto armor work too

**Comment by northrix** [comment]
and i used it on 1.12 and 1.12.2 spigots
here are the console errors for 1.12 version
Debug uploaded to p.reflex.rip
https://p.reflex.rip/X7FX

Dump uploaded to p.reflex.rip
https://p.reflex.rip/GNKL.md

Server log uploaded to p.reflex.rip (or it's part with console error if reporting a console error)
https://p.reflex.rip/o3Ze.go


Reflex log uploaded to p.reflex.rip
https://p.reflex.rip/b4UR.vbs

its important for me to use it on 1.12 so any solutions?

**Comment by MeGysssTaa** [comment]
**1.12** errors were already reported here: #217 
Those will be fixed in the next update, please wait a few days^^.
