### ISSUE TITLE
Flase positive kicked for hacking

### ISSUE THREAD

**Issue by jehuntminecraft** [MeGysssTaa/ReflexIssueTracker#225]
Kick ID: #BWILQM22  2018.01.22

I was running around moving items from chest to chest using a beacon with Speed II and also flying down 6 blocks a lot using an elytra. I then proceeded to rapidly kill a bunch of slimes with an axe. I was kicked while killing slimes.

I am using Optifine 1.12.2 HD U CB and no other mods to my client.

![screenshot from 2018-01-22 05 34 24](https://user-images.githubusercontent.com/35688965/35220364-1901dcfe-ff44-11e7-8cc3-1a56b714d0e8.png)

**Comment by johand199** [comment]
Could you give us the verbose or the logs?

**Comment by Janmm14** [comment]
The kick id is local to your server and only refers to your logs.

**Comment by MeGysssTaa** [comment]
https://github.com/MeGysssTaa/ReflexIssueTracker/blob/master/CONTRIBUTING.md
