### ISSUE TITLE
A huge problem with the whole anticheat

### ISSUE THREAD

**Issue by AivaruxxLTU** [MeGysssTaa/ReflexIssueTracker#226]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass/false positive/bug/console error/feature request/question

>  BUG

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

> https://p.reflex.rip/oSeL

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

> https://p.reflex.rip/cefn.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

> No error at all.

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

> https://p.reflex.rip/bCCY.vbs

### Erase everything written below if this is not a bypass or a false positive report
**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

> 

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

>  It's the whole anticheat not working. Everything bypasses and no NPC's exist

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

>  https://www.youtube.com/watch?v=6LZnNeM7Km4&feature=youtu.be

**OTHER**

Additional information which you think might be useful for solving the issue faster

>

**Comment by MeGysssTaa** [comment]
Your configuration is invalid:
![Screenshot](https://sc.reflex.rip/pY4HUv.png)

**Comment by AivaruxxLTU** [comment]
I didnt change anything. Whats wrong??

**Comment by MeGysssTaa** [comment]
Everything. Your config is empty.
Reset it.
