### ISSUE TITLE
Many false positives on the killaura detection

### ISSUE THREAD

**Issue by Alexre** [MeGysssTaa/ReflexIssueTracker#227]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞  False positive

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/1p4H

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/7mA4.md (after the pvp of the video provided)

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ 

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞  https://p.reflex.rip/OB9d.vbs (is the log of the pvp)

### Erase everything written below if this is not a bypass or a false positive report
**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ Just fight, it detects every player pvp as killaura, I left the anticheat on a server and it banned almost 200 players in 10h.

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞ 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://youtu.be/Np6J7zMkZZs

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ Reflex is detecting every pvp as killaura, tried it with all my staff in a closed server, maybe is because the ping, they are from us and the host is from france

I take the opportunity to say that the custom theme does not work, I can't change it, as you can see theme: 'ModernBlue_ES' is showing EN messages.

**Comment by MeGysssTaa** [comment]
It appears that you all have very decent lag there. Nothing we can really do about it. If most of your players are from the US, I'd suggest you moving your host there so that players have no discomforts.

Please keep in mind that the new lag accounting system is currently experimental and is planned to be improved in future. However, that will simply reduce the chance of lagging players getting these high numbers of violations. Unfortunately, it's impossible to make everything work perfectly with irregularly high latencies.

If your staff members are the only US players, feel free to simply give them the *reflex.bypass* permission.
