### ISSUE TITLE
Killaura FP

### ISSUE THREAD

**Issue by Hyronymos** [MeGysssTaa/ReflexIssueTracker#23]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other): Killaura false positive

Server version: 1.8.8

ProtocolLib version: 4.20

Reflex version: 10.0-1U

ViaVersion version (if present): 1.0.3

A video proving the bypass/false positive if reporting a bypass/false positive: https://youtu.be/YTDXarn4Am8

A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive: https://pastebin.com/VSKmtRtb

Its looks like the FP is only in void worlds

**Comment by Janmm14** [comment]
Ohnemaus

**Comment by MeGysssTaa** [comment]
Your server seems to **have scripts or plugins that delete folders/files or copy them from templates**. This leads to the logs being cleared. Try to specify another directory for Reflex (the `general.working_dir` value), or develop an own logging system using Reflex API.
