### ISSUE TITLE
Blockaction -> Silent not work

### ISSUE THREAD

**Issue by H1rntot** [MeGysssTaa/ReflexIssueTracker#235]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ bug

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ Blockactions:
>  The Silentcheck does not work. When it is "true" it also block all Actions.

**Comment by MeGysssTaa** [comment]
Please include **/reflex debug** and video-evidence.
