### ISSUE TITLE
Severe FPs with Protocol Support in 1.5.2 client 

### ISSUE THREAD

**Issue by iedesu** [MeGysssTaa/ReflexIssueTracker#236]
## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞This Plugin's Killaura detction is awesome, but when I run it with protocolsupport,
users in 1.5.2 has severe FP with killaura check; immediately detect legit as a hacker
especially check G / Analyse.

So hope this helped to your protocolsupport support

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ 

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ 

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ 
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 1 (+1) type G?ping: 0?lp: 144 (extreme lag)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 1 (+1) type G?ping: 0?lp: 144 (extreme lag)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 2 (+1) type G?ping: 0?lp: 41 (minor lag)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 7 (+7) type G?ping: 0?lp: 41 (minor lag)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 14 (+7) type G?ping: 0?lp: 13 (ok)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 23 (+9) type G?ping: 0?lp: 13 (ok)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 32 (+9) type G?ping: 0?lp: 13 (ok)?tps: 19,99
(Reflex/DEBUG) | 「Reflex」RemIsDead KillAura 41 (+9) type G?ping: 0?lp: 13 (ok)?tps: 19,99
(Reflex/DEBUG) | Dispatching command reflex%space%kick%space%RemIsDead%space%§fYou%space%have%space%been%space%kicked.%break%§fReason:%space%§b§lDETECTED%space%FOR%space%HACKING§r%break%%break%§r§cIf%space%you%space%believe%space%that%space%this%space%is%space%a%space%false%space%positive,%break%§cplease%space%open%space%a%space%report%space%at%space%§fgo.reflex.rip/bug§r%break%%break%§7Kick%space%ID:%space%§f#5V4HJN87%break%§72018.02.09 (execution id: #5V4HJN87)

### Erase everything written below if this is not a bypass or a false positive report

By reporting a false positive, I confirm that I have entirely read and understood the contents of [the False Positives article](https://goo.gl/R93HQy) on this issue tracker, and that I will follow everything stated there.

**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ just open server with 1.11.2 server and put reflex / protocollib latest / protocolsupport latest
    and join with 1.5.2 client, that's all.
    after that, if you hit some other players twice or a little more, you will get false kick as soon.

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞ 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ just test it and you will immediately notice it

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞

**Comment by MeGysssTaa** [comment]
Reflex has not, does not, will not and can not support versions before 1.8 (especially 1.5.2, lol), sadly.

**Comment by iedesu** [comment]
i know but what i am saying about is server with protocol support
