### ISSUE TITLE
InvActions Always Enabled

### ISSUE THREAD

**Issue by elstur** [MeGysssTaa/ReflexIssueTracker#238]
I have tried setting this to silent and it still seems to be stopping actions (and closing people out of chests and crafting tables).

I then disabled it, reloaded and even restarted but I am still getting verbose notifications about InvActions even with enabled set to false.

**Comment by MeGysssTaa** [comment]
Please provide **/reflex debug** output and a video-evidence.

**Comment by elstur** [comment]
https://p.reflex.rip/qsVo

Can't do a video atm but still get InvAction notifications.

**Comment by MeGysssTaa** [comment]
Please also provide your server log after startup.

**Comment by elstur** [comment]
Maybe after my next restart. Too many people online to do it right now. I can show this if it helps:
https://imgur.com/a/r9I6f

Just to show I am still getting these notifications.
