### ISSUE TITLE
A lot of false positives

### ISSUE THREAD

**Issue by JavituRec** [MeGysssTaa/ReflexIssueTracker#244]
**ISSUE TYPE**

A lot of false positives

Faction log: https://gist.github.com/JavituRec/06728715031dcbcba4bfe8cf182ece46

Kitpvpv log: https://gist.github.com/JavituRec/1bbd1231c7b92eb91bfa8a54da441563

Skywars log: https://gist.github.com/JavituRec/9ba1c365eb5e96e6e9407bfdeda80a64

**EVIDENCE**

https://drive.google.com/file/d/1Rg-7jEGOiTOldJ5e5-qz7SOGv9i3ZlIo/view

https://youtu.be/P3DeqxGoB2A

https://drive.google.com/file/d/1I4E1ELjbLTZR3rIimlTY0u0T_5H9brH4/view

https://youtu.be/vkIqu_9mxjQ

**EXTRA INFORMATION**
Server version: 1.8.8
Reflex version: 10.4-1U

**Comment by pEwViktor** [comment]
https://youtu.be/P3DeqxGoB2A this video you can see the person trying to hit the anticheat bots so its not counted as a fp.

**Comment by MeGysssTaa** [comment]
Reflex is not compatible with plugins that have impact on combat mechanics (MCMMO in your case, I guess).

**Comment by JavituRec** [comment]
I only install mcmmo in faction but 4/5 server where I installed Reflex.

I post logs of Kitpvp and Skywars, I do not have any plugin of skills installed or any incompatible plugin that is detailed in the overview page

What seems to me to be absolutely unpropitious is that it is based on a part of this report only to close this report and to leave nothing else.

**Comment by MeGysssTaa** [comment]
All of the posted videos with false positives are from Factions.

**Comment by JavituRec** [comment]
https://www.youtube.com/watch?v=vkIqu_9mxjQ&feature=youtu.be

**Comment by JavituRec** [comment]
I'm going to upload more videos about false positives other than server factions soon.

**Comment by MeGysssTaa** [comment]
A few hits being canceled cannot be called a 'false positive' — please read **[this article](https://github.com/MeGysssTaa/ReflexIssueTracker/blob/master/FALSE_POSITIVES.md)**.
If you want Reflex to do completely no combat impact, feel free to enable the **silent** setting.
