### ISSUE TITLE
Exited out of chat and guis from reflex.

### ISSUE THREAD

**Issue by MrWardy** [MeGysssTaa/ReflexIssueTracker#245]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ BUG

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/hfMK

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/KWXS.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/iWfC.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/ss0f.rb

### Erase everything written below if this is not a bypass or a false positive report

Bug description
> When a player opens chat, or any gui they are exited out of said chat or gui at a random time. I'm led to believe that this is due to reflex (for whatever reason) teleporting the player to his/herself as the screen slightly shakes before exiting out of the chat or gui.

Video
In attached files...
I've compressed the video to .zip since gtihub attachments don't support mp4.
[Reflex Bug.zip](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1799624/Reflex.Bug.zip)

I believe this issue is caused due to an incompatible plugin but I am not 100% sure and if it is I have no idea which plugin it is.

**Comment by MeGysssTaa** [comment]
Your configuration is invalid. You need to reset it.
![i](https://sc.reflex.rip/zMPz.png)

**Comment by MrWardy** [comment]
I've just deleted the Reflex config and let it regenerate, the same thing still happens.
Here's my config here: https://p.reflex.rip/Txue.coffeescript

**Comment by MeGysssTaa** [comment]
Please try again without Reflex. If it stopped happening, then try disabling Reflex's checks one by one to see which one is causing this bug.

**Comment by MrWardy** [comment]
I've removed reflex and it doesn't happen. I'll try the checks
