### ISSUE TITLE
entity raytrace FP

### ISSUE THREAD

**Issue by 8Marc8** [MeGysssTaa/ReflexIssueTracker#247]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

**false positive**

＞ 

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

We tested Reflex and found out, that you can earn this fp by hitting a player frequently with your hand.

Youtube: https://youtu.be/lFfnTL3GWjc

**## https://p.reflex.rip/DooY.pl**

**Comment by MeGysssTaa** [comment]
Disable `killaura.realistic_entityids`.
