### ISSUE TITLE
Player getting kicked to bungeecord hub

### ISSUE THREAD

**Issue by Toxcity** [MeGysssTaa/ReflexIssueTracker#249]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ bug

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/DZdZ

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/7Irr.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/FCd5.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/9Eco.rb

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://youtu.be/eNm3UdD1vDY

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ This bug does not consist when reflex is not enabled or the killaura check is disabled. This issue makes the plugin 100% unusable and would be greatly appreciated if this could be resolved. If you need additional information please contact me at my discord (Toxcity#2422) before closing the issue. Thank you for your assistance.

**Comment by Hyronymos** [comment]
#165

**Comment by johand199** [comment]
![7e207cd7-341d-449e-b744-72f4966fc650](https://user-images.githubusercontent.com/6952369/37571998-bfc878fe-2b04-11e8-8bc4-1930bb2d7766.png)
Video is not available, you mind reuploading?

**Comment by Toxcity** [comment]
okay one sec

**Comment by Toxcity** [comment]
it was on private for some reason, should be better now.

**Comment by VerifiedDuck** [comment]
Yea seems to be affecting some few people and makes the plugins unusable.

**Comment by Toxcity** [comment]
:/

**Comment by yyunusyigit** [comment]
@MeGysssTaa , The problem continues.

**Why and how does this problem occur?**

1.  Your server has to be a BungeeCord.
2.  The KillAura check must be active.
3.  X player must hit Y player.
4.  Reflex will spawn NPC for control.
5.  X player tries to hit this NPC.
6.  Yes, you are kicking now.

**How can you solve this problem?**

1. When the player is kicked, an error log occurs. (BungeeCord)

Error log: https://hasteb.in/abinuhed.lua

We expect you to solve the problem. We bought it today and can not use it because it kicked the players. This is a very sad situation.
I wish you success!

**Comment by MeGysssTaa** [comment]
@yyunusyigit can you please use `/reflex packetdebug` several (3-5) times on **one (same)** player and attach those here? You can do that like:

1. Player joins
2. You do `/reflex packetdebug toggle <player>`
3. Let the player hit someone until disconnect.
4. You will get a message saying the packet debug file was created.
5. Repeat 3-5 times.

This will give us useful information regarding the packets that are possible the cause of the issue ^^.

**Comment by yyunusyigit** [comment]
@MeGysssTaa , Thanks for information.

Report 1:  https://p.reflex.rip/5N7Z
Report 2:  https://p.reflex.rip/9GNO
Report 3:  https://p.reflex.rip/PvIw
Report 4:  https://p.reflex.rip/LoFE
Report 5:  https://p.reflex.rip/XFot

Report video:  https://www.youtube.com/watch?v=ZJkO5Gz2p2w&feature=youtu.be

And a question:  As you see in the video, why is the score table and player tag deleted?

**Comment by yyunusyigit** [comment]
@MeGysssTaa , If they were not helpful;

I can print all packets sent to the player for BungeeCord. More clear results will emerge.

**Comment by yyunusyigit** [comment]
BungeeCord Packet Debug:

https://hasteb.in/ojetihed.cs
