### ISSUE TITLE
Not hit

### ISSUE THREAD

**Issue by JavituRec** [MeGysssTaa/ReflexIssueTracker#250]
**ISSUE TYPE**
bug:

Player can't hit other

**EVIDENCE**
https://www.youtube.com/watch?v=IXBxjVqAXdc&feature=youtu.be

Server version : 1.8.8
Reflex version: last

**Comment by MeGysssTaa** [comment]
Please provide your /reflex debug, server and Reflex logs.

**Comment by JavituRec** [comment]
Reflex debug:
https://p.reflex.rip/k4kq

Reflex log:
https://gist.github.com/JavituRec/45e38194f18021dd3a25302275134eed

Server log:
https://gist.github.com/JavituRec/02a66ae6abfc5b4a7684825d1bf239a0

And the message appear in EN when I have selected in config:
ModernBlue_ES

**Comment by MeGysssTaa** [comment]
Can you send the Reflex logs regarding the situation in the video?

**Comment by JavituRec** [comment]
The log that I have passed is from that same day

**Comment by JavituRec** [comment]
I will try to reproduce this error again to report more securely. Forget this report until I answer again.
