### ISSUE TITLE
[Idea] Configurable VL per Check

### ISSUE THREAD

**Issue by 8Marc8** [MeGysssTaa/ReflexIssueTracker#252]
Hello,

it would be awesome if there's the possibility to change the increased VL of each check. Type J for example increases the VL by 100. If you set the kick at 28VL it's an instant kick. With a configurable VL you could take more control over the kick-behaviour of reflex.

**Comment by MeGysssTaa** [comment]
This is the reason the checks are combined together for. Trusted or long checks kick instantly, while those which are meant to have FPs every 5-10 hits add only a few points.
