### ISSUE TITLE
KillAura false positives

### ISSUE THREAD

**Issue by JavituRec** [MeGysssTaa/ReflexIssueTracker#253]
**ISSUE TYPE**
False positives

**LOGS**
Debug: https://p.reflex.rip/0ZZM

Logs Reflex1: https://gist.github.com/JavituRec/78f7dd3cb805c710d22185ad22f5d62b

Log Reflex2: https://gist.github.com/JavituRec/98dae23d19bc16125176e2e3fd905e9e

**EVIDENCE**
Reflex1: https://youtu.be/4B5e72W8wN8?t=1m17s "KICK ID: #U6IWQN0C"

Reflex2: https://youtu.be/IYstEPgj10o "KICK ID: #B33Z0KSU"

**Comment by johand199** [comment]
Looks like he is having some lag issues, you can see multiple times when the enemy is close to him but server won’t accept his hits due to his lag. At times looking at all logs he has 360+ ping

I would in my opinion try ConditionalCommands for better lag accounting

**Comment by JavituRec** [comment]
Reflex has its own lag leniency system, for that I must know from which ping the users could have false positives and know what rank I must upload to be expelled.
