### ISSUE TITLE
Disabled checks aren't changed when using `/reflex reload`

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#256]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats Reflex checks and which it doesn't. I clearly understand that there are no movement checks at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## Report
**Issue**
> Bug

##

**Description**
> When adding or removing entries from the disabled checks list, using the command `/reflex reload` has no effect on the setting

**Comment by MeGysssTaa** [comment]
Reflex isn't actually meant to be compatible with any sort of reloading. The point of the `/reflex reload` command is to update changed minor settings like messages or some numbers; it does not cover some stuff.
