### ISSUE TITLE
Reflex bot pushing because it cant go below your y level

### ISSUE THREAD

**Issue by poppoppo** [MeGysssTaa/ReflexIssueTracker#260]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ bug

 https://www.youtube.com/watch?v=EaTTKfqa3go&feature=youtu.be

This video shows 3 minutes of me getting harassed by bots, for the simple reason that the bot is unable to go below your y level, meaning that if you look straight up the bot will be shaking inside your body, constantly randomly pushing you. All that has it be changed is to allow the bot to go below the players y level, and then it will never be able to push you since when you look up it will be under you instead of being in your body.

**Comment by SirGoldman-git** [comment]
Having the same issue, did you find a way to resolve it yet?

**Comment by poppoppo** [comment]
No, currently i suspect a different unknown plugin i have telling the game to allow player pushing. I have it turned off in both reflex and via version. If you find a solution to this please let me know. Or we can just wait for an update with the fix i described.
