### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#264]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats Reflex checks and which it doesn't. I clearly understand that there are no movement checks at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## Report
**Issue**
> Console Error

**Description**
> Self-explanatory 
More details can be provided if requested

##

**Logged Error**
> https://p.reflex.rip/05qE.md

**Comment by johand199** [comment]
![close](https://user-images.githubusercontent.com/6952369/39512665-1c11cc72-4df2-11e8-9c12-c0ce12487326.png)
