### ISSUE TITLE
Very serious bug that is crashing the server

### ISSUE THREAD

**Issue by Encode17** [MeGysssTaa/ReflexIssueTracker#266]
I have noticed 3 crashes of my server up from 2 days. I did not referenced it with Reflex, but then, server generated crash log and gave me stacktrace.
Using spigot 1.12.2 and java 1.8.

Console stacktrace:  https://pastebin.com/ifYczJzt
Crashlog: https://pastebin.com/ka5NFQYs

Crash is probably because reflex is causing chunk unload not in main thread.
https://hub.spigotmc.org/jira/browse/SPIGOT-3300

Please, fix it as fast as it is possible.

**Comment by MeGysssTaa** [comment]
Seems to be a bug we can do nothing with. A possible workaround would be adding `ka.ad` to `killaura.disabled_checks`.

**Comment by Encode17** [comment]
I think that soultion is easier than you think. Just shedule unload to main thread.

new BukkitRunnable(){
  public void run(){
    <chunk unload HERE>
  }
}.runTask(yourPluginClass);

**Comment by MeGysssTaa** [comment]
The solution in our case doesn't exist. It doesn't work like that. You can still disable the component.
