### ISSUE TITLE
CPU Load Problem

### ISSUE THREAD

**Issue by Blackbird1604** [MeGysssTaa/ReflexIssueTracker#269]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ Question

Hello,

i got a question. Im using PaperSpigot 1.8..8 and Reflex in Combination with AAC (AAC does the checks which Reflex doesnt), now i have the problem that when Reflex is enabled the cpu load rises and after ca. 24h the cpu load is on 100%.

On my Hostmachine about 40 Servers are running and the normal cpu load is ~ 10%.
Its a Dual Xenon Hexacore  2.3Ghz Machine with a total of24 Threads.

If you need more Information, please tell me!

**Comment by MeGysssTaa** [comment]
Cloud will likely solve that.

**Comment by Blackbird1604** [comment]
If a Dual Xenon Hexacore cant handle this, then i dont understand.
A Dual Xenon Hexacore 24 Threads, 96GB Ram should handle this, shouldnt it?
And the CPU Load rises overnight, so its weird so why does it rise even when 0 players online?

**Comment by MeGysssTaa** [comment]
Doesn't matter what CPU you have. Machine learning takes lots of RAM, especially with many servers.

**Comment by MeGysssTaa** [comment]
I'd suggest you getting a Cloud trial first, that helps in most cases.

**Comment by Blackbird1604** [comment]
I suggest i will talk to md_5 first if this is serious what happens here...
