### ISSUE TITLE
False positive when fighting in water.

### ISSUE THREAD

**Issue by CraftG** [MeGysssTaa/ReflexIssueTracker#274]
## General
**ISSUE TYPE**

＞ False positive

Debug

＞https://p.reflex.rip/bh2a

Dump

＞ https://p.reflex.rip/hQkf.md

Reflex log

＞ https://p.reflex.rip/7Wwk.sql

GIF:

＞ https://www.sendspace.com/file/hlx56g

Sorry, I can't upload to Youtube

**Comment by MeGysssTaa** [comment]
Please try resetting your config (delete `/Reflex/config.yml`). If the issue still persists please try it on Spigot, not Torch.
