### ISSUE TITLE
Problem with nohitdelay-customknockback

### ISSUE THREAD

**Issue by Niketion** [MeGysssTaa/ReflexIssueTracker#276]
false positive

**REFLEX DEBUG & REFLEX DUMP LINKS**
https://p.reflex.rip/cAh4

**DESCRIPTION**
Setting of [CustomKnockbak](https://www.spigotmc.org/resources/custom-knockback.39113/)
```
horizontal_multiplier: 0.243
y_multiplier: 0.175
sprint_multiplier: 1.5
kb_fix: true
```
Delay's nohitdelay is 5

**EVIDENCE**
https://youtu.be/IHV6VTiB7dU

**Comment by Niketion** [comment]
After 3/4 second I was kick for Killaura

**Comment by MeGysssTaa** [comment]
We don't support custom knockback, custom hit delay and versions below 1.8.
