### ISSUE TITLE
Reflex Thinks Im a Pirate ARRRRG GIMME UR BOOTY DarkSide!

### ISSUE THREAD

**Issue by YaBoiSpec** [MeGysssTaa/ReflexIssueTracker#277]
## General
**ISSUE TYPE**

bug／console error

＞  Console error, Its quite aids as it wont let reflex load :_(... it says Im a pirate ARRRRG!

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/JK9C.sql

How are you using hastebin...without hastebin link?!?!?! Redirect?

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞  I used vanilla to bypass reflex cuhz its not working l0l0l0l0l

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ Cannot provide evidence if I cannot load reflex! derp!

[Discord TOS doesnt prevent Spec from using this awesome plugin]

**Comment by YaBoiSpec** [comment]
Im sure fiona and spartan are not causing piracy error.... I mean I hope not lul...

Config: None / Default

Other plugings:
ProtocolLib
Fiona
Spartan

Spigot Version
1.8.8 Spigot.jar [1.8R3]

**Comment by YaBoiSpec** [comment]
Arrrrg common I know this is showing up in your discord and tagging you like crayz

**Comment by YaBoiSpec** [comment]
@DarksideSkid#1491  Gimme ur booty !

**Comment by MatrixTunnel** [comment]
Can you please stop spamming? Darkside is currently offline but he will get to you.

Continually sending messages doesn’t make time go any faster

**Comment by YaBoiSpec** [comment]
Yes discord bot we know that sending messages doesnt make darkside get magnatized to his keyboard any faster.... He has a life... We know

**Comment by MeGysssTaa** [comment]
@YaBoiSpec What's your Spigot username?

**Comment by YaBoiSpec** [comment]
Jonathan_HA

**Comment by YaBoiSpec** [comment]
Personally wish I could change it

**Comment by YaBoiSpec** [comment]
If you want I can provide proof of purchase via screenshots of my paypal, and spigot purchases, and reflex overveiw

**Comment by YaBoiSpec** [comment]
@MeGysssTaa

**Comment by MeGysssTaa** [comment]
Please try again.

**Comment by YaBoiSpec** [comment]
okay

**Comment by YaBoiSpec** [comment]
Gotta run some errands so it may be a bit

**Comment by YaBoiSpec** [comment]
Thanks for making my reflex copy registered finally
