### ISSUE TITLE
Reflex | Console errors [10.7.1 - Latest]

### ISSUE THREAD

**Issue by yyunusyigit** [MeGysssTaa/ReflexIssueTracker#283]
[Spigot: 1.8.8 | BungeeCord | ViaVersion | Reflex Latest]

Console errors: 
https://p.reflex.rip/6EiT.lua

Other error:
1.8.8 server, when player is logged in with version 1.12.2 (Maybe other versions of 1.9+ are also included.)  :  At the time of PvP, the score board and the teams are deleted.

A screenshot: http://prntscr.com/k9heis

**Comment by MeGysssTaa** [comment]
The console errors are already known.
Regarding scoreboard bugs, try setting `killaura.disable_collisions` to `false`.
