### ISSUE TITLE
Block Actions FP/bug (disconnects with no warning)

### ISSUE THREAD

**Issue by literallyEllie** [MeGysssTaa/ReflexIssueTracker#289]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ false positive /  bug?

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/Stdd

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/tBRp.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/yuEk.rb

### Erase everything written below if this is not a bypass or a false positive report

By reporting a false positive, I confirm that I have entirely read and understood the contents of [the False Positives article](https://goo.gl/R93HQy) on this issue tracker, and that I will follow everything stated there.

**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ Mine blocks (Always happened with a stone pickaxe) on stone 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://youtu.be/Jrdjkk3Yio4
Person ripp'd https://www.youtube.com/watch?v=2rGPz43Fg9Y

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ No but this error has literally crushed a release. This error didn't happen when we had to disable it.

**Comment by literallyEllie** [comment]
Proxy console error that happens: https://p.reflex.rip/1Mz8.lua (forgot to tag) 

I researched this error and it was linked to either a broken server jar (we are using a stable Paper spigot release) and or a plugin that is doing stuff with packets.

**Comment by MeGysssTaa** [comment]
Please enable the `sync_npcs` option in `killaura` settings section and restart your server.

**Comment by literallyEllie** [comment]
Happened again:

「Reflex」danb76 BlockActions 5 (+5) type L・cancel・ping: 0・lp: 17 (ok)・tps: 20,0・comp: blckact.sfd

**Comment by MeGysssTaa** [comment]
Are players still being disconnected?

**Comment by literallyEllie** [comment]
Yep. Exact same output and outcome.

**Comment by MeGysssTaa** [comment]
Do the disconnects still happen if you disable the BlockActions check?

**Comment by literallyEllie** [comment]
![bilde](https://user-images.githubusercontent.com/9784635/43738359-a261a234-99c4-11e8-9a1d-ff5439174342.png)
Debug: https://p.reflex.rip/QgX1

I don't know why it is not showing much, here is the config the server is running https://pastebin.com/Ar3eqvBr

**Comment by MeGysssTaa** [comment]
Do the disconnects still happen if you disable the BlockActions check?

**Comment by literallyEllie** [comment]
> Yes

**Comment by MeGysssTaa** [comment]
Please try adding `ka.fe` and `ka.ffd` to the `killaura.disabled_checks` list.

**Comment by literallyEllie** [comment]
In the process we got this, triggering a disconnect due to the same Empty Packet error as before.
Still trying to reproduce the Block actions ones
![bilde](https://user-images.githubusercontent.com/9784635/43768967-e727d9a0-9a38-11e8-8a14-6e1215251f05.png)

**Comment by literallyEllie** [comment]
Ok after fixing a small config error, which your plugin didn't seem the need to say, and that disable coming into effect wasting about 15 minutes of our lives, we concluded that it is not reoccurring, however we couldn't say for certain due to the randomness of it and that neither of us really know what triggers it.

**Comment by literallyEllie** [comment]
That does appear to work yes; but now we have no real protection from anticheat etc.

**Comment by literallyEllie** [comment]
https://hastebin.com/jebaqisise.coffeescript

**Comment by literallyEllie** [comment]
Proxy error snip: https://hastebin.com/wewenilema.bash
A startup log: https://hastebin.com/uhesuwiciz.sql
Latest reflex log: https://hastebin.com/acotucuruc.rb

**Comment by MeGysssTaa** [comment]
Oh, sorry, forgot you have killaura check disabled. Could you enable it back (just set `killaura.enabled` to `true`) and send the **server log** (and nothing else) again?

**Comment by literallyEllie** [comment]
https://hastebin.com/opucokujin.sql

**Comment by MeGysssTaa** [comment]
Can you try if this still happens with this ProtocolLib? 
https://workupload.com/file/7tjNF4m

**Comment by literallyEllie** [comment]
When the KA checks (fe and ffd) were still disabled, yes. But when I renabled them I was eventually again kicked whilst I was just standing there and my friend was trying out with a hacked client + getting for the same Empty Packet reason, however he was flagged + exempted for "Bad Packet" (badkpcks.rrn) then instantly disconnected with "Empty Packet".

**Comment by MeGysssTaa** [comment]
Well, the only thing I can recommend in this case is probably to keep the `ka.fe` and `ka.ffd` components disabled ._.

**Comment by literallyEllie** [comment]
¯\_(ツ)_/¯ thanks anyway I guess.
