### ISSUE TITLE
why not support UTF-8  ?

### ISSUE THREAD

**Issue by minhthanh920** [MeGysssTaa/ReflexIssueTracker#293]

**Comment by MeGysssTaa** [comment]
??

**Comment by minhthanh920** [comment]
i using theme ModernBlue_VI but reflex message alway showing incorrect UTF-8 character

**Comment by MeGysssTaa** [comment]
Do you mean in your server console?

**Comment by minhthanh920** [comment]
its in-game

**Comment by MeGysssTaa** [comment]
That's something wrong with you. Likely because your server or your client doesn't support utf-8. Reflex does not and cannot affect the way the characters are displayed.

**Comment by MatrixTunnel** [comment]
@minhthanh920 Something is wrong with your setup. Try adding `-Dfile.encoding=UTF-8` to your server startup arguments
