### ISSUE TITLE
Reflex for modified Spigot

### ISSUE THREAD

**Issue by Damdamdu95** [MeGysssTaa/ReflexIssueTracker#297]
I have a question, I use nSpigot-Entreprise (a modified spigot), this spigot modifies the kb and more. If I buy Reflex, will it support this version of spigot with all the features of the anticheat?

**Comment by Janmm14** [comment]
If I remember correctly, modified knockback is not supported by reflex.

See first compatibility point listed in the **Installation** section:
https://www.spigotmc.org/resources/%E3%80%8Creflex%E3%80%8Dmachine-learning-cheat-detection-%C2%BB-1-8-1-12.21122/
