### ISSUE TITLE
High Ping

### ISSUE THREAD

**Issue by eliasjtg** [MeGysssTaa/ReflexIssueTracker#3]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False Positive

**Server version:**
?

**ProtocolLib version:**
?

**Reflex version:**
10.0

**ViaVersion version (if present):**
?

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://www.youtube.com/watch?v=fIClgFipSAg

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
?

**Additional information (e.g. how to reproduce the issue you are experiencing):**
I entered the server with high ping and end by kicking for hack, what happened to these limits?

**Comment by MeGysssTaa** [comment]
Should be solved now. Can you retest this when you get time?
