### ISSUE TITLE
Kicked for "server is still starting up" and Console Error

### ISSUE THREAD

**Issue by briang112** [MeGysssTaa/ReflexIssueTracker#300]
## General
**General**

Bypass／false positive／bug／console error／feature request／question

＞  False Positive / Console Error
[24-09-2018.log](https://github.com/MeGysssTaa/ReflexIssueTracker/files/2409735/24-09-2018.log)

## Unexpected plugin behavior report

Plugin kicks users for "server is still starting up, please wait!" infinitely. Plugin also has errors in console at startup.

**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/qyt2

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞  https://p.reflex.rip/G8iY.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/Xdcb.md 

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞  https://p.reflex.rip/d1Ad.rb

**Comment by MeGysssTaa** [comment]
Sorry, Reflex does not support 1.13 yet.
