### ISSUE TITLE
Reflex verbose format language improvement

### ISSUE THREAD

**Issue by TheWranger** [MeGysssTaa/ReflexIssueTracker#305]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ Feature Request

It would be nice if we could have a standalone ping variable and a standalone tps variable for the `verboseFormat` line in the theme file. I would like to shorten down the verbose message as many of the tags can't really be diagnosed or properly used by my server moderators.

Thanks.

**Comment by MeGysssTaa** [comment]
Hello,

Verbose **should not be used by server moderators**, but by **us (Reflex developers)**. The whole purpose of those messages is to help us (the developers) investigate users' issues. Moreover, it is only needed when reporting bugs.

**Comment by TheWranger** [comment]
But then what do we give to server moderators to allow them to help identify cheaters manually?

**Comment by MeGysssTaa** [comment]
The intention of anticheats is to identify cheaters automatically, moderators don't need to. Reflex will simply kick players it believes are hacking itself.
