### ISSUE TITLE
False positive with killaura bot

### ISSUE THREAD

**Issue by Zeyyphox** [MeGysssTaa/ReflexIssueTracker#31]
## Reflex Bug Report
Issue type : False positive

Server version: spigot-1.8.8-R0.1-SNAPSHOT.jar

ProtocolLib version: I always have the last one available

Reflex version: 10.0-1U

Proof : https://www.youtube.com/watch?v=wwSa_ZNfXIQ&feature=youtu.be

Additional information : I've used Wolfram for test the new Reflex but I wasn't using any cheats in the video, so it's really a false positive

**Comment by MeGysssTaa** [comment]
Not really a false positive because you have tried to get kicked.
Will be fixed later, but giving it very low priority.
