### ISSUE TITLE
False Positives on a lot of hacks

### ISSUE THREAD

**Issue by PolarGamingMC** [MeGysssTaa/ReflexIssueTracker#313]
First killaura is a BIG false positive second It doesnt kick me but it says in the verbose the I have anti-Knockback because when I was hit back by a player I was holding W

The killaura I have no idea why it's kicking me

**Comment by drkousek** [comment]
Hey. Did you read it....? Video... without video is nearly impossible recreate your issue...

**Comment by Janmm14** [comment]
doesnt kick me = no real false positive too

**Comment by MeGysssTaa** [comment]
Please take a look at [https://g.reflex.rip/contributing](this guide) and create a new, valid issue.
