### ISSUE TITLE
[1.13.2] Client NPE Disconnect

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#318]
**Issue:**
> Bug

**Debug Link:** 
> https://p.reflex.rip/uqer

**Details:**
> When hitting a player you get disconnected for
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException`
after the npcs spawn. There are no other errors besides that single line

##

**Server Version:**
> Paper/git-Paper-510 (MC: 1.13.2)

**Client Version:**
> 1.8.9 (connected using ProtocolSupport)

##

**Agreement:**

By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in the [guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats Reflex checks for, and which it does not. I clearly understand that there are no movement checks or similar at this time. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or Paper. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

**Comment by MeGysssTaa** [comment]
I'm unable to reproduce the issue with this setup:
![](https://png.sx/zAIb)

My tests were:
- player1 joins the server;
- player2 joins the server;
- player1 attacks player2 -> everything is fine;
- player2 attacks player1 -> everything is fine.
Both players are using the same MC version (1.13.2 + OptiFine).

**Comment by MeGysssTaa** [comment]
It's a ProtocolSupport issue (or at least a sort of a protocol conversion issue). Nothing I can really do. For 1.12x servers, use ViaRewind/ViaBackwards instead. For 1.13x, I guess you should wait for those plugins to update.

**Comment by MatrixTunnel** [comment]
ProtocolSupport for works fine for 1.12 and 1.13 servers with 1.8 clients but it's just the spawning of NPCs using Reflex while running on 1.13 servers that causes the disconnect

**Comment by MeGysssTaa** [comment]
Reflex + 1.13.2 + **backwards compatibility with ProtocolSupport** = incompatible, that's what I mean.

**Comment by MatrixTunnel** [comment]
Try removing ViaVersion and testing again. It appears that 1.13 clients get disconnected for the same reason
