### ISSUE TITLE
Denizen support

### ISSUE THREAD

**Issue by Noiknez** [MeGysssTaa/ReflexIssueTracker#321]
## General
**ISSUE TYPE**

feature request

＞ Greeting, my server use the Denizen scripting langague and I would like Reflex to support this plugin :
eg: Everything that is detected/fired/modified by this plugin 

Plugin page : https://www.spigotmc.org/resources/denizen.21039/

Regards

**Comment by Noiknez** [comment]
Denizen is like the more knowed plugin "Skript" its like a scripting engine. There is a big list of mechanism that modify block, player status and such (speed of the player, etc ...)
--> https://one.denizenscript.com/denizen/mecs
The support that would be nice would be "everytime that a mechanism is changed by the plugin Denizen, then there is no activation or false positive"

**Comment by MeGysssTaa** [comment]
Please tell me the exact "mechanisms" and the exact "false positives" they cause for that^^
I sadly have no time for testing third-party plugins fully myself.

**Comment by Janmm14** [comment]
@MeGysssTaa I think its more about reflex api being available through that scripting language.

**Comment by Noiknez** [comment]
I use almost all the mecanism here :
- https://one.denizenscript.com/denizen/mecs
And command here (like "cast" for example)
- https://one.denizenscript.com/denizen/cmds/
I have remade many plugin into this language and want to use Reflex, the problem is for every command/mecanism it modify heavily the gameplay (also with NMS)
Sorry .. I can't tell you the exact things .. I want to make sure I can use Denizen without problem with Reflex before I buy it

Regards

**Comment by Noiknez** [comment]
Oh ok I also modify this
`non-vanilla combat (hit range/angle/delay, knockback, and other) mechanics.`
:/
