### ISSUE TITLE
It will be kicked if you beat the AFK person

### ISSUE THREAD

**Issue by yuki72312** [MeGysssTaa/ReflexIssueTracker#330]
(Google translate)
You will be kicked if you hit a player who is AFK
Any way of hitting will happen

Video
https://www.youtube.com/watch?v=s3C-UmXqQEI&feature=youtu.be
PluginVersion 10.9-1U

**Comment by MeGysssTaa** [comment]
Hello,

(1) Please write `/reflex debug`. It will give you a link. Send that link here.
(2) Please send me your latest Reflex log file (`your-server-folder/plugins/Reflex/logs/20-03-2019.log`).

**Comment by yuki72312** [comment]
debug link: https://p.reflex.rip/saso
log file: [20-03-2019.log](https://github.com/MeGysssTaa/ReflexIssueTracker/files/2986372/20-03-2019.log)

**Comment by poppoppo** [comment]
I noticed you have the plugins ViaRewind and ViaBackwards, is your server based on 1.7? If it is, that might be the cause of the issues, since reflex does not support 1.7.
Try switching to 1.8, and see if you still have the same problems

**Comment by yuki72312** [comment]
(Google translate)
I used 1.8.8.
I pulled out what was pointed out but did not fix

**Comment by MeGysssTaa** [comment]
Please try to set `realistic_entityids` to `false`

**Comment by MeGysssTaa** [comment]
I assume that your issue is solved since you are not responding anymore.
Feel free to reopen it if it's not.
