### ISSUE TITLE
Disabling Reflex due to piracy.

### ISSUE THREAD

**Issue by LinkGamingYT** [MeGysssTaa/ReflexIssueTracker#331]
ISSUE TYPE

bug／console error

＞ Console error, > [08:04:29 INFO]: (Reflex/WARN) | Disabling Reflex due to piracy. If you believe that this is an issue, make sure to open a report at go.reflex.rip/bug

Server log uploaded to p.reflex.rip (or it's part with console error if reporting a console error)

＞ https://p.reflex.rip/aroy.shell

EVIDENCE

A video that starts by enabling /reflex verbose and demonstrates the existence of the bypass/false positive uploaded to YouTube

＞ I cannot provide any evidence if the plugin cannot load to the server.

Spigot Name: Mekdonald
Spigot link to profile: https://www.spigotmc.org/members/mekdonald.615075/

**Comment by MeGysssTaa** [comment]
Your license has been terminated due to leaking.
We already had a talk about that on Spigot in DMs. You will be unbanned in one week.

**Comment by LinkGamingYT** [comment]
Do you have Discord?

**Comment by MeGysssTaa** [comment]
Yes, https://g.reflex.rip/discord
