### ISSUE TITLE
Killaura false Positive in test srever

### ISSUE THREAD

**Issue by CowzMooMoo** [MeGysssTaa/ReflexIssueTracker#341]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

false positive／bug／

＞ False Positive

**DESCRIPTION**

When i was testing on the test server, I got false kicked. I started recording and reproduced the false positive on tape. 

What do you need to do to reproduce the false positive (only for FP report) 

＞ Zeroday B17 Hacked Client. (1.8)

**EVIDENCE**

＞ https://www.dropbox.com/s/pgfrrs5s2rbp5oj/ZeroDay%204_2_2019%205_08_13%20PM.mp4?dl=0

**Comment by MeGysssTaa** [comment]
Hello,

as stated in [this guide](http://g.reflex.rip/fps), we do not accept false positives reports where:
(a) a non-vanilla client is being used;
(b) the reporting player is fighting an "AFK" entity (an entity being fully in inaction) for a long period of time;
(c) the reporting player is attempting to look like a cheater purposefully.
