### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by Hyronymos1337** [MeGysssTaa/ReflexIssueTracker#347]
Server-Log: https://privatebin.net/?44a693f9b193e29e#fcoYO13iHXqXgOtTwSpGWKK5VWCj0O6LGBQV0aAn8YA=

Server Version: 1.8.8 PaperSpigot

Newest Reflex Version

**Comment by Janmm14** [comment]
config file contains char with hexadecimal notation 0x90 which cannot be read by yaml
(somewhere inside a string)
