### ISSUE TITLE
Bad content of packets - "animation type 1" that does not exist in Minecraft. It causes errors and kicks on checks when using ProtocolSupport

### ISSUE THREAD

**Issue by MorkaZ** [MeGysssTaa/ReflexIssueTracker#349]
Using latest reflex, spigot 1.13.2 and bungeecord.
All details are there:
https://github.com/ProtocolSupport/ProtocolSupport/issues/1086

Please, fix it. I can not use it on my server because of this bug.

**Comment by MeGysssTaa** [comment]
Try adding `ka.ffd` and `ka.fe` in the `killaura.disabled_checks` list in config

**Comment by MeGysssTaa** [comment]
#357 related probably
