### ISSUE TITLE
 A BadPackets component badpcks.rtg is disabled.

### ISSUE THREAD

**Issue by rushserverforwanybuild** [MeGysssTaa/ReflexIssueTracker#354]
When I start server,
I found a WARN message that say 
" A BadPackets component badpcks.rtg is disabled. It is highly recommended that you report bugs at go.reflex.rip/bug rather than turn the checks off! Support regarding bypasses will not be providen in case there are disabled components."
What happened?

/reflex debug : https://p.reflex.rip/uhek
[https://i.postimg.cc/4NTbQKx8/image.png](url)

**Comment by MeGysssTaa** [comment]
Hello,

This is an unfinished component that we forgot to disable in code due to rush for the update, so we disabled it in config. Just ignore this warning^^
