### ISSUE TITLE
Killaura (Heuristics) False Positive

### ISSUE THREAD

**Issue by CowzMooMoo** [MeGysssTaa/ReflexIssueTracker#358]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ False Positive

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/uhul

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/xase.md

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/amac.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/pafa.sql (I was testing stuff before, just scroll to bottom)

### Erase everything written below if this is not a bypass or a false positive report

By reporting a false positive, I confirm that I have entirely read and understood the contents of [the False Positives article](https://goo.gl/R93HQy) on this issue tracker, and that I will follow everything stated there.

**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ A 1.8.8 paper spigot server, optifine 1.8.9, 6 CPS~, a jittery aim

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞ 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://www.youtube.com/watch?v=dMkxzq4YDjw&feature=youtu.be (I was jittering more to make the detection quicker, although this false positive does still happen with less jittery aim, it just takes longer.)

**EDIT** I was testing a bit more and after a little bit this happened: https://www.youtube.com/watch?v=XjN9v69LX3M&feature=youtu.be (Insanely quick false positive)

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ Yes, although I use a "custom" spigot jar, the PvP settings are unmodified from vanilla PvP settings (Kb). I also use killaura Heuristics Severity 1, but it is advertised to have "rare false positives" so I am reporting this false positive

**Comment by CowzMooMoo** [comment]
**Side note:** This cannot be reproduced on the public test server due to the Killaura Heuristics being at severity 2.

**Comment by CowzMooMoo** [comment]
**Side note** This cannot be reproduced on the test server because it is on Heuristics severity 2

**Comment by MeGysssTaa** [comment]
@CowzMooMoo The description to "severity 1" clearly says that false positives may take place, that's the price you pay for stricter killaura/aimbot detection. I'd strongly recommend you using "severity **2**" instead (and that's the **default** config value since **10.11**).

**Comment by CowzMooMoo** [comment]
The description of "severity 1" states it has "rare false positives" - from what I can tell, it is extremely unstable... 

However on the SpigotMC page, you advertise to "Detect the undetectable" and detect "Vape aimassist legit 140%" and that is not achievable with serverity 2 heuristics.
