### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by WizzPLVG** [MeGysssTaa/ReflexIssueTracker#36]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Server version:**
1.7.10

**ProtocolLib version:**
3.7.0

**Reflex version:**
10.0

**ViaVersion version (if present):**
no

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://hastebin.com/ifufuwadoy.md (video incoming)

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
https://hastebin.com/ifufuwadoy.md

**Additional information (e.g. how to reproduce the issue you are experiencing):**

**Comment by OWERLORD01** [comment]
xD

**Comment by WizzPLVG** [comment]
lol fuck off

2017-05-25 20:51 GMT+03:00 OpenSource <notifications@github.com>:
