### ISSUE TITLE
Reflex not working when testing

### ISSUE THREAD

**Issue by MattyBoi69** [MeGysssTaa/ReflexIssueTracker#362]
Hello,

Sorry if I am doing this wrong.

But whilst testing the latest build of reflex on my server, I am not op'ed whilst testing, and the anticheat is not picking up on any hacks. The config is the same as it is when the plugin is installed.

Any reason why this is happening ?

**Comment by Janmm14** [comment]
Which cheats are you trying?
Did you look into the console for potential errors?

**Comment by MattyBoi69** [comment]
Hi,

When I do /reflex help there is an issue in console, we tried all hacks that are listed. 

We are running Spigot 1.12, with latest PLib, and latest REFLEX version

**Comment by Janmm14** [comment]
So mind about sharing what the console spits out on startup and/or on /reflex, so that the developers of reflex can fix it?

**Comment by MeGysssTaa** [comment]
Please send your full server log (`latest.log`) @MattyBoi69 
And what's your Java and server version?
