### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by PaperJun** [MeGysssTaa/ReflexIssueTracker#363]
I am learning Java I want know how to create a fake player for check killaura, I want use it to my plugin. I already purchased Reflex. Can you tell me the code for create a fake player? thank you!
Because spigotmc official website I can't bypass the firewall so I can't give you I purchased prove.
![4UG_DK`5 S%~@G8BC(NY~3D](https://user-images.githubusercontent.com/58140733/81781290-79a14a80-952a-11ea-9997-2d1eb5623812.png)

**Comment by MeGysssTaa** [comment]
Hello,

Sorry, but Reflex source code or any of its parts are **not** included in the purchase. Our NPC checks are quite complicated so we cannot share them with you.

In a nutshell, those "bots" are shown to specific players using **packets (ProtocolLib)**. If you are just starting to learn Java, that will be pretty difficult to implement. I'll suggest you start with something more simple and then follow various ProtocolLib tutorials/wikis. After feeling confident enough with the Minecraft protocol, you can create whatever you want referring to https://wiki.vg/

**Comment by PaperJun** [comment]
You can write a code for me not reflex it's ok I really need this.
If you can can you write a fake player likes watchdog?
