### ISSUE TITLE
Please, dear author

### ISSUE THREAD

**Issue by PaperJun** [MeGysssTaa/ReflexIssueTracker#364]
(My English is bad sorry)
(Before I have a issue but you closed this conversation.)
https://github.com/MeGysssTaa/ReflexIssueTracker/issues/363
please, I really need the code of create fake player like Reflex or watchdog. :(
I am learning Java but I want do this, Please! :( :(
You can not share your code of Reflex. :1st_place_medal:

**Comment by PaperJun** [comment]
Please, dear author! I want create the fake player like your Reflex!!! :((

**Comment by MeGysssTaa** [comment]
https://bukkit.org/threads/packets-npcs-protocollib.221025/
https://www.spigotmc.org/threads/npc-spawning-protocollib.228832/
