### ISSUE TITLE
[FP] Multiple hitbox +20 (period) in 2 occasions

### ISSUE THREAD

**Issue by LightninSky** [MeGysssTaa/ReflexIssueTracker#376]
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/Sjdqvb). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/Sjdqvb) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ False positive

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

### Keep empty only if this is a feature request or a question or if the issue is reported from test.reflex.rip
**REFLEX DEBUG & REFLEX DUMP LINKS**

Debug uploaded to [p.reflex.rip](https://p.reflex.rip)

＞https://p.reflex.rip/sopo

Dump uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ 

Server log uploaded to [p.reflex.rip](https://p.reflex.rip) (or it's **part with console error** if reporting a console error)

＞ https://p.reflex.rip/afeb.md

Reflex log uploaded to [p.reflex.rip](https://p.reflex.rip)

＞ https://p.reflex.rip/obog.sql

### Erase everything written below if this is not a bypass or a false positive report

By reporting a false positive, I confirm that I have entirely read and understood the contents of [the False Positives article](https://goo.gl/R93HQy) on this issue tracker, and that I will follow everything stated there.

**DESCRIPTION**

What do you need to do to reproduce the false positive (only for FP report) 

＞ Long fights with jitterclick

Which client and which settings do you use to bypass **(NO DOWNLOAD LINKS!)** (only for bypass report) 

＞ 

**EVIDENCE**

A video that starts by enabling **/reflex verbose** and demonstrates the existence of the bypass/false positive uploaded to [YouTube](https://youtube.com) 

＞ https://youtu.be/sEzrpsIpuRk

**OTHER**

Additional information which you think might be useful for solving the issue faster

＞ Not sure if it matters, I was using Lunar Client for this one (Footage recorded on Sunday, July 19th 2020 at 10-11pm GMT-5)

Pd: I feel this false positives I'm reporting happen in specific scenarios (Like long fights non stop, Nodebuff, Gapple kind of matches, this one specifically looked to emulate a gapple match, a 1v1 match where the players eat notch golden apples and fights until the armor breaks, that's why the health level is set so high)... I know this is not related to this report, but I tried recreating the previous ka.ra issue, I did after half an hour (You can see on the reflex logs) but I lost the footage, I'll keep trying to get more footage of it.

**Comment by MeGysssTaa** [comment]
The hitbox check will be replaced with a new one in 11.0.
