### ISSUE TITLE
It has no effect, only misjudgment.

### ISSUE THREAD

**Issue by vlssu** [MeGysssTaa/ReflexIssueTracker#383]
A plug-in can at least have a certain degree of defensive ability, instead of making the player unable to understand how to use it. In just a few days after the purchase, I not only did not anti-cheat, but instead imposed various restrictions on the players who did not open the hook. And cheating adjusted all the parameters to the highest level, and the anti-cheating began to restrict him. Until now, I don't know whether AI learning is turned on or not. He has no effect. The documentation is very messy and complicated, and I can't find out how to use them. It's too unfriendly. This is the least friendly of all plugins I have ever bought.
Difficult to use and incomplete documentation, I want to refund now, but I can't find where the refund button is. Because he is of no use to me now.
Instead, players are very dissatisfied with this.

**Comment by MeGysssTaa** [comment]
Hi! Can you exactly describe what issues are you facing? What is lacking/messy in the documentation? If you're talking about false positives (the anticheat kicking legit players from the server), please provide some information such as `/reflex debug` and *verbose* (detailed information about Reflex activity — you can find it in your server logs or [use Reflex's Cloud Verbose feature](https://g.reflex.rip/cloud-verbose)).

By the way, I'd also recommend you to [join our Discord](https://g.reflex.rip/discord) for faster, live support :)
