### ISSUE TITLE
NPCs

### ISSUE THREAD

**Issue by XReioX** [MeGysssTaa/ReflexIssueTracker#384]
## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ Feature request

If this is a question or a feature request, please erase everything written below and write your suggestion/question text.

Add random armor to the npc, so killaura what only attacks players with armor will still attack the npc.

**Comment by MeGysssTaa** [comment]
Hi! Reflex NPCs mimic nearby online players by default. Therefore, if there are no players nearby who wear armor, the NPCs won't either. You can change this behavior to more random with `killaura.realistic_playerdata`, but this will actually make the check way easier to bypass, so I don't recommend it.
