### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by 1145141919** [MeGysssTaa/ReflexIssueTracker#4]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False Positive

**Server version:**
idk(test server)

**ProtocolLib version:**
idk(test server)

**Reflex version:**
10.0

**ViaVersion version (if present):**
idk(test server)

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://sendvid.com/r5ew8rhp

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
None

**Additional information (e.g. how to reproduce the issue you are experiencing):**
ign:Nintendo_Wii time:GMT 02:18-02:19      Kaliningrad Time  04:18-04:19

**did you test hacks before?**
yes.

**Comment by MeGysssTaa** [comment]
Were you legit all the time you tested? Or did you test hacks before? Need that for logs.

**Comment by 1145141919** [comment]
did you test hacks before?:yes

**Comment by 1145141919** [comment]
another video http://sendvid.com/4qiyqv90
Kick ID:LF-148698266
