### ISSUE TITLE
FalsePositive KillAura (Angle) (Type M)

### ISSUE THREAD

**Issue by Vktre** [MeGysssTaa/ReflexIssueTracker#42]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False Positive

**Server version:**
1.8 and more.

**ProtocolLib version:**
Newest probably (test server)

**Reflex version:**
Reflex-U2

**ViaVersion version (if present):**
Test servers version.

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://u.nya.is/jcgiqe.mp4

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
Servers.

**Additional information (e.g. how to reproduce the issue you are experiencing):**
Falsely kicked me, may be different without speed.

**Comment by MeGysssTaa** [comment]
That's incompatibility with Essentials's /speed.

**Comment by Vktre** [comment]
Yea.
