### ISSUE TITLE
False positive killaura

### ISSUE THREAD

**Issue by mentir64** [MeGysssTaa/ReflexIssueTracker#46]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
false positive

**Server version:**
1.8.x

**ProtocolLib version:**
4.2.1

**Reflex version:**
10.0u-01

**ViaVersion version (if present):**
yes

**A video proving the bypass/false positive if reporting a bypass/false positive:**
https://youtu.be/xcnSfyn3mKs

**Comment by Eyremba** [comment]
Wtf everything from 1:48 on is unnormal combat.
