### ISSUE TITLE
Reflex: NullPointerException

### ISSUE THREAD

**Issue by byCaptain** [MeGysssTaa/ReflexIssueTracker#48]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**

**Console Error**

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

https://prnt.sc/fetgl1
http://prntscr.com/fethuh

**Comment by byCaptain** [comment]
http://prntscr.com/fey8sc

**Comment by MeGysssTaa** [comment]
Where's /reflex debug link?
