### ISSUE TITLE
1.11 disconnect issue

### ISSUE THREAD

**Issue by timothydavidhart** [MeGysssTaa/ReflexIssueTracker#49]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Random player kicks

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://pastebin.com/XuGY1NPt

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Just hit players and get kicked nothing much to it

**Comment by MeGysssTaa** [comment]
Why did you skip the /reflex debug item? You must fill that.
Also please provide the disconnect message you get on client.
