### ISSUE TITLE
1.11 disconnect issue

### ISSUE THREAD

**Issue by Sollembum78** [MeGysssTaa/ReflexIssueTracker#57]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Any fighting, with or without cheats disconnects player with error, screenshot below. Few hits with normal vanilla or wurst result in this.

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
This command results in something I can not understand, full server log is here
https://pastebin.com/EfKVy59h

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
https://pp.userapi.com/c637328/v637328455/4de26/oBbJXFvJllw.jpg
https://pp.userapi.com/c637328/v637328455/4de2f/9bkq3PkSHAY.jpg

**Comment by MeGysssTaa** [comment]
/reflex debug is working now, do it again please.

**Comment by Sollembum78** [comment]
It still gives me Moved Permanently, I restarted server just in case. Do I have to do something else to make it work?
https://pastebin.com/SJQwwK6T

**Comment by MeGysssTaa** [comment]
Hm, we'll take look, though it works for me.
May you send the following info manually, please?

1. Full server version (/version), including the "You are N versions behind" string.
2. ProtocolLib version (/ver ProtocolLib), ViaVersion version (if present).
3. A complete plugins list (/plugins).

**Comment by Sollembum78** [comment]
This server is running CraftBukkit version git-Spigot-3fb9445-fbb47e8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
You are 40 version(s) behind
ProtocolLib version 4.2.1-SNAPSHOT-b346
Plugins (31): Skript, OpenInv, ExertSK, TuSKe, FarmLimiter, ProtocolLib, Reflex, MultiWorld, skRayFall, FastAsyncWorldEdit, MundoSK, PermissionsEx, SQLibrary, hub, skUtilities, mcMMO, Vault, RandomSK, HideStream, WorldEdit, Essentials, CompatNoCheatPlus, mcMMOAction, WorldGuard, NoCheatPlus, EssentialsProtect, EssentialsAntiBuild, ServerSigns, EssentialsSpawn, SharpSK, AdvancedAbilities

https://pastebin.com/JKXBcxA0
https://pastebin.com/bpjg1TSZ

Versions and plugin list is different on other servers (as our bungee contain 40+ servers) but problem is same everywhere.

**Comment by MeGysssTaa** [comment]
Can you start the client with enabled console and send it's contents (or just your client log) after kick?

**Comment by Sollembum78** [comment]
https://pastebin.com/n2jdggke

**Comment by MeGysssTaa** [comment]
Have you got discord or any other easier way to contact? xd

**Comment by Sollembum78** [comment]
Telegram Kamino_Ramos, vk.com/kamino_ramos, skype: sollembum78

**Comment by MeGysssTaa** [comment]
Check your skype, added you with a link to this issue
