### ISSUE TITLE
Huge TPS loss

### ISSUE THREAD

**Issue by TheIronMinerLv** [MeGysssTaa/ReflexIssueTracker#59]
So the only thing what I changed is I disabled both SSL in config.yml, then put it in server and it seemed to work. When I let my players in, the TPS dropped to 8 and here are just a screenshot from timings: http://prntscr.com/fg3718

Full timings: https://timings.aikar.co/?id=791b3dcb7d3f468ebb8abf77bc1ef2b5

I would like to have this fixed by doing so: Version 9.9 worked awesome for me (I just used to send "notifications" in chat, it wouldn't kick anyone), but last night something happened, so the server couldn't start. Here are the error which blocked the server startup: https://pastebin.com/8HWBseGg Please fix this and I'll be happy, currently version 10 is much much more buggier than 9.9.

**Comment by Eyremba** [comment]
> currently version 10 is much much more buggier than 9.9.

Maybe because V10 is a whole recode of it?!

> Here are the error which blocked the server startup: https://pastebin.com/8HWBseGg

As you can see: 

> [Reflex] Disabling Reflex v9.9

And that's normal, because we only support versions above 10.

**Comment by Eyremba** [comment]
> Here are the error which blocked the server startup: https://pastebin.com/8HWBseGg Please fix this 

Dude this error is from Reflex 9.9, which is no longer supported.
