### ISSUE TITLE
On player join error

### ISSUE THREAD

**Issue by TheIronMinerLv** [MeGysssTaa/ReflexIssueTracker#65]
Just installed fresh newest Reflex, it seems it works, but there are this error every time someone joins the server: https://pastebin.com/YdTbGrLW

Paperspigot 1.8.8 with viaversion. Played on 1.11.2

**Comment by Eyremba** [comment]
Thanks for your report!

The stacktrace has been deobfuscated and was sent to the developers.

Please give them some time to check it.

**Comment by MeGysssTaa** [comment]
Have you got a cracked (online-mode=false) or premium (online-mode=true) server?

**Comment by TheIronMinerLv** [comment]
Cracked
