### ISSUE TITLE
Killaura Angle False Positive

### ISSUE THREAD

**Issue by Scuffi** [MeGysssTaa/ReflexIssueTracker#66]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
False Positive

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/ypnp

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://pastebin.com/EdC8sfBq

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Most of the verbose messages were 'angle' 3 were 'reach' and one was 'entity raytrace'

**Comment by MeGysssTaa** [comment]
A video is required.

**Comment by MeGysssTaa** [comment]
Issue is closed as of no further info provided.
