### ISSUE TITLE
Again TPS loss

### ISSUE THREAD

**Issue by TheIronMinerLv** [MeGysssTaa/ReflexIssueTracker#67]
The same problem as in https://github.com/MeGysssTaa/ReflexIssueTracker/issues/59: TPS drops to 14, this is NOT normal. **PLEASE LET ME USE REFLEX 9.9**, it didn't had any problems, but now I can't use it, because it shows something about "can't check for legacy" or something like that when I use 9.9 version...

Here are the timings: https://timings.aikar.co/?id=19c53c27b79d450187a86ac62d487336

I'm using newest Reflex with fresh configuration (disabled all kicks and stuff), paperspigot 1.8.8.

**Comment by MeGysssTaa** [comment]
Reflex 9.9 should be working, if it doesn't, please send what exactly it sends.
The performance problems are caused by obfuscation. We're trying our best to solve this.

**Comment by TheIronMinerLv** [comment]
In 4th june my server wasn't able to start, so for many hours it tried to start many many times, but it failed (so my server wasn't available for many hours). https://pastebin.com/hdvRJHz8

I will test again tomorrow, but I don't want to have that issue again...

**Comment by MeGysssTaa** [comment]
Are you able to record some Reflex timings with the latest version on Reflex on your server please?
/reflex timings on
-- Wait some (10-15) seconds while someone or you is fighting --
/reflex timings save
Then send here the file that has been created in "/reflex/directory/that/you/specified/timings/".

**Comment by TheIronMinerLv** [comment]
I removed the plugin, so unfortunately I can't provide such information. What about my previous comment? Is that 9.9 version fixable? I really loved it, because it didn't lag and also was more configurable (max CPS)...

**Comment by MeGysssTaa** [comment]
Reflex 9.X versions were only down for 1 or 2 days. And no, 10.0 is much more configurable ^^. We've just hidden all the settings so unexperienced users won't break it and then spam us with "omfg I disabled everything and put all on minimum and now wurst bypasses"-like 1 star ratings.

**Comment by TheIronMinerLv** [comment]
So theoretically I can use 9.x version if want? And there won't be a such issue anymore?

**Comment by MeGysssTaa** [comment]
Yes, you can use it.

**Comment by Eyremba** [comment]
> So theoretically I can use 9.x version if want?

However, be aware of the fact the 9.x version is not so good in terms of detection and that there are a few bypasses for it. 10.X is much better.

**Comment by jiangdashao** [comment]
You can try other obfuscation tools like Allatori

**Comment by Eyremba** [comment]
> You can try other obfuscation tools like Allatori

Dude are you fucking kidding me? Allatori can be read and deobfuscated easily. We need heavy protection.

Also, you should stay out of this topic, and leave this topic up to us developers.

**Comment by TheIronMinerLv** [comment]
When there could be an update that would fix these lag issues?

**Comment by Eyremba** [comment]
> When there could be an update that would fix these lag issues?

Most likely in the next few days.
