### ISSUE TITLE
Killaura false positive + Criticals bypass

### ISSUE THREAD

**Issue by shnxtom** [MeGysssTaa/ReflexIssueTracker#70]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Killaura false positive + Criticals bypass

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

https://youtu.be/FgcAaK5wn3A
**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by Eyremba** [comment]
Wtf dude everything is perfect. All kind of combat violations will raise the Killaura violations, that's why you got kicked. You got kicked because the Criticals raised up your Killaura violations. That's it.
