### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by M4T14SG4M3R** [MeGysssTaa/ReflexIssueTracker#71]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
This didn't gave me any link, it says Creating debug paste then Already collecting and nothing happen

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
Not going to do a video, it's only a console error

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
https://pastebin.com/Rk4YD8nW
https://pastebin.com/nZqFurup
https://pastebin.com/ijSf6BaF
This happened when someone logged in

**Comment by MeGysssTaa** [comment]
Please provide the following infos:
- [ ] Server version (/ver).
- [ ] ProtocolLib version (/ver ProtocolLib).

**Comment by M4T14SG4M3R** [comment]
This server is running PaperSpigot version 1.7.10-R1.1
ProtocolLib version 3.7-SNAPSHOT-b232
