### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by lolo773** [MeGysssTaa/ReflexIssueTracker#75]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console Error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
Didn't have any messages.

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
28.06 23:51:36 [Server] WARN Exception in thread "Craft Scheduler Thread - 7" 
28.06 23:51:36 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Reflex v10.0-3U generated an exception while executing task 413
28.06 23:51:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
28.06 23:51:36 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
28.06 23:51:36 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
28.06 23:51:36 [Server] INFO at java.lang.Thread.run(Thread.java:745)
28.06 23:51:36 [Server] INFO Caused by: rip.reflex.zC: e

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by Vktre** [comment]
You should provide more information as; server version, protocolib version, plugins.
