### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Zykreh** [MeGysssTaa/ReflexIssueTracker#76]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/VkIZ

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://pastebin.com/GbTwViNV

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
idk, i was just testing it with aimassist

**Comment by Zykreh** [comment]
Also, /reflex ban not working no matter what i put in it https://pastebin.com/9WK7B0pk

**Comment by Zykreh** [comment]
ProtocolLib version: 4.3.0
Plugin list: Reflex, ProtocolLib
Spigot version: git-Spigot-6e32d18-8e5e4c1 (MC: 1.8.3)

**Comment by MeGysssTaa** [comment]
How do you use the /reflex ban command? Send me what do you enter in chat.

**Comment by MeGysssTaa** [comment]
Please type /reflex ban to see it's usage..
