### ISSUE TITLE
Uegkillbot bypassing anti-kb check?

### ISSUE THREAD

**Issue by johand199** [MeGysssTaa/ReflexIssueTracker#83]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
bypass

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
https://p.reflex.rip/UZfy

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://youtu.be/hpSqDixbNcs

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Test server

**Comment by MeGysssTaa** [comment]
Not a bypass since he's getting vertical knockback.
