### ISSUE TITLE
Console Task Error

### ISSUE THREAD

**Issue by Tiippex** [MeGysssTaa/ReflexIssueTracker#92]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console task error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
creates this error: https://hastebin.com/osusiyudav.bash

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
https://hastebin.com/xelejiledu.css

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
simply hit another person

Spigot 1.8.8
ProtocolLib: http://ci.dmulloy2.net/job/ProtocolLib/378/

**Comment by MeGysssTaa** [comment]
Invalid ProtocolLib version. Please read the overview page.
