### ISSUE TITLE
Random Kick Bug

### ISSUE THREAD

**Issue by MatrixTunnel** [MeGysssTaa/ReflexIssueTracker#94]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error / other

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
No thing in the logs, just this https://pastebin.com/qQYjDbe8
https://gfycat.com/CreepyIndelibleDingo

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
Java: 1.8.0_131
Server: Paper/git-Paper-1152 (MC: 1.12)
Reflex: 10.1-1U
Protocollib: 4.3.1-SNAPSHOT-b378

**Comment by mariolars** [comment]
I have same issue: https://pastebin.com/SWcUHzQf

**Comment by Hij310** [comment]
I have it too:

http://i.imgur.com/fucAiFt.png
http://i.imgur.com/GDBbah6.png
http://i.imgur.com/kOo3TiK.png

**Comment by MeGysssTaa** [comment]
@MatrixTunnel @mariolars @Hij310 does this still happen if you set **global.bad_meta** to **false** in Reflex config? (This setting is missing by default. You need to add it yourself)

**Comment by Hij310** [comment]
@MeGysssTaa Unfortunately, it does not solve it

**Comment by MatrixTunnel** [comment]
Sorry I'm a bit late to responding but setting `bad_meta` in global did actually fix the problem. The scoreboards broke for some reason after the first npc starting flying around, but that might just be an issue on my end.

**Comment by MeGysssTaa** [comment]
@MatrixTunnel does this still happen if you enable (or cut away) this option back and install ViaVersion (not for cross-versioning, but for automated packet translation)?
