### ISSUE TITLE
[Request] Toggle Entities from Kill-Aura check

### ISSUE THREAD

**Issue by elstur** [MeGysssTaa/ReflexIssueTracker#95]
**# Request: Toggle Entities**
Allow a config option to toggle the use of entities in the Kill-Aura checks.

No matter what the Entity settings are changed to (to be clear, I have no nametag plugins since you mentioned this in forums), they are not currently 100% invisible. They last an incredibly long duration and I find this interrupting enough that I have to disable the whole kill-aura check which I would prefer not to. 

A way to toggle these entities off would be very much appreciated.

**Comment by jiangdashao** [comment]
But if you disable it,check will be slow.....

**Comment by Eyremba** [comment]
> they are not currently 100% invisible.

Omfg dude that's what they are made for. If they would be invisible, then the clients would NOT hit them!

And if you would disable them, then the detection would be slow as fuck.

**Comment by MeGysssTaa** [comment]
Entities can be made always invisible by setting npc_visibility_time to 0. If it doesn't work please record a video and create a proper bug report.

**Comment by elstur** [comment]
Filing a bug report does not change this suggestion. If you are unwilling, just explain why instead of being so disrespectful.

**Comment by Eyremba** [comment]
> Filing a bug report does not change this suggestion. If you are unwilling, just explain why instead of being so disrespectful.

Dude stfu I already explained you that disabling the entities would slow down the detection of bad clients!

**Comment by elstur** [comment]
You mean your deleted comment that I can't read? GG.

See the word "Toggle" in the suggestion? That indicates if you want to use it for those bad clients, you go right ahead. I'm not interested in the use of entities and I want them disabled.

**Comment by Eyremba** [comment]
> I'm not interested in the use of entities

This means, you are not interested in banning cheaters.
