### ISSUE TITLE
[Request] Add labymod to mod detection

### ISSUE THREAD

**Issue by elstur** [MeGysssTaa/ReflexIssueTracker#96]
# **Rquest: Labymod in Mod Detection**

In your newest update you added mod detection. This was a great new feature and I was hoping you would add Labymod to your support list on this. They have an API much like 5zig and the other mods you have support for to allow detection to happen.

Also, any mod that reverts to 1.7 animations that you can detect would be awesome too.

**Comment by MeGysssTaa** [comment]
LabyMod cannot be detected. It only allows to disable some of it's features. We'll probably add this later.

**Comment by MatrixTunnel** [comment]
This API was just recently released to allow communication between the server and LabyMod client easily
https://github.com/LabyMod/labymod-server-api

**Comment by elstur** [comment]
@MeGysssTaa 
Was there a reason this was dropped?

**Comment by MatrixTunnel** [comment]
I thought it was added

**Comment by MeGysssTaa** [comment]
There's already an official plugin for that: https://www.spigotmc.org/resources/labymod-server-api.52423/

**Comment by elstur** [comment]
There is for all the other client control stuff too, I just like the way you lay out your config options. I guess labymod has much more detail though.

Thanks anyway.
