### ISSUE TITLE
Performence issue

### ISSUE THREAD

**Issue by jiangdashao** [MeGysssTaa/ReflexIssueTracker#97]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Reflex used too much CPU

this is timings:
[timings-2017.07.23_05-23-23.txt](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1167873/timings-2017.07.23_05-23-23.txt)

**Comment by jiangdashao** [comment]
[dump-1500769694774.txt](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1167956/dump-1500769694774.txt)
[timings-2017.07.23_08-28-07.txt](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1167957/timings-2017.07.23_08-28-07.txt)
Send file again

**Comment by MeGysssTaa** [comment]
Cloud Computings solve the issue.
